### ISSUE TITLE
Verification in the form and return of "success" when submitting the form

### ISSUE THREAD

**Issue by rayanepimentel** [Tech-N-Science/FunwithScience#135]
**Is your feature request related to a problem? Please describe.**
It's not a problem. And yes an improvement in the form

**Describe the solution you'd like**
Simple verification in the name and message field (more than one character) and in the email field.
The message "successfully sent", when submitting the form, could be a "toasts"

**Additional context**
This update could be for Hacktoberfest

**Comment by Amit366** [comment]
@rayanepimentel can u link it to gmail?? Like when someone sends some message then it should be received in form of email

**Comment by Amit366** [comment]
@rayanepimentel r u working??

**Comment by rayanepimentel** [comment]
@Amit366 Hi, sorry for the delay.
I will start now.

**Comment by MrSingh2000** [comment]
Can you please update on the current status for that issue, especially about the integration of email verification.

**Comment by Amit366** [comment]
@MrSingh2000 basically when user clicks on send in the contact form then it should be received in the form of mail
