### ISSUE TITLE
Atomic Physics Section

### ISSUE THREAD

**Issue by akashsahu006** [Tech-N-Science/FunwithScience#147]
**Is your feature request related to a problem? Please describe.**
The atomic physics section page could be created with few formulas so that others can start adding more to it.

**Describe the solution you'd like**
A page of atomic physics should be created just like the classical mechanics one. And some calculators can be added, so other people can start contributing to it.

**Comment by akashsahu006** [comment]
Can you assign this to me?

**Comment by Amit366** [comment]
@akashsahu006 which calculators will u add??

**Comment by akashsahu006** [comment]
I can add the calculators for Bohr's radius of the orbit,  velocity of the electron, frequency of the electron, another calculator for calculating potential, kinetic and total energy. And one for frequency of emitted radiation.

**Comment by Amit366** [comment]
Ok go ahead. @akashsahu006

**Comment by Amit366** [comment]
@aakankshabhende by when can u send the PR??

**Comment by Amit366** [comment]
@akashsahu006 r u still working on this issue??
