### ISSUE TITLE
Reset Button

### ISSUE THREAD

**Issue by Amit366** [Tech-N-Science/FunwithScience#153]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
1) Change the calculate and reset buttons(on calculator page) to smaller size so that both buttons can be side by side.
2) calculator are zoomed out to be responsive which is not good, fix that
3) In mobile view, for some calculators the page reloads from the middle, fix it

**Comment by imakish** [comment]
I would like to work on this issue.

**Comment by aditya-rastogi23** [comment]
I'd like to work on this, can you assign me to this?

**Comment by aditya-rastogi23** [comment]
I'll have a look and check, I think I should be able to do it
