### ISSUE TITLE
Electrostatics

### ISSUE THREAD

**Issue by Amit366** [Tech-N-Science/FunwithScience#154]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Add calculator for electrostatic(electric field and electric potential) in current electricity topic.

**Comment by souravseal99** [comment]
can I work on this ?

**Comment by shivaprasadyanala** [comment]
Yes

**Comment by souravseal99** [comment]
> @souravseal99 u can work but first send the PR of other issues

Please check the PR regarding the thermodynamics issue, and let me know why it's still open ! @Amit366 ?

**Comment by Amit366** [comment]
@souravseal99 where is the PR??
