### ISSUE TITLE
There is a problem in sign up and login code as after registering it take into login page but on login it's showing invalid login credentials. I think there is some problem in your backend code. I can try to solve it.

### ISSUE THREAD

**Issue by ShivamAgarwal-code** [Tech-N-Science/FunwithScience#327]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ShivamAgarwal-code** [comment]
Can I take up the issue?

**Comment by Amit366** [comment]
@ShivamAgarwal-code thanks for raising this issue. But mostly it works fine. I didn't find such error. Have u tried with the deployed site?

**Comment by ShivamAgarwal-code** [comment]
@Amit366 yes I have tried with deployed site.
![WhatsApp Image 2022-01-18 at 11 06 57 AM](https://user-images.githubusercontent.com/72163800/149877336-fe3abc4f-85f5-4092-89d2-a0545dc66dd9.jpeg)

![WhatsApp Image 2022-01-18 at 11 08 04 AM](https://user-images.githubusercontent.com/72163800/149877345-f731bfc9-4a14-42a2-8449-3200824ba954.jpeg)

**Comment by Amit366** [comment]
@ShivamAgarwal-code ok then u can work

**Comment by SayanDeveloper** [comment]
Yes I have also faced the same error issue.

**Comment by Amit366** [comment]
@ShivamAgarwal-code are u working on it?

**Comment by ShivamAgarwal-code** [comment]
Yes

**Comment by Amit366** [comment]
@ShivamAgarwal-code can u send the PR by today?

**Comment by ShivamAgarwal-code** [comment]
sorry but I will send soon, actually I will be working on it for diversion.

**Comment by ShivamAgarwal-code** [comment]
@Amit366 is theren't any php code for login page?

**Comment by Amit366** [comment]
@ShivamAgarwal-code the backend link is in the folder funwithscience-backend

**Comment by ShivamAgarwal-code** [comment]
otherwise i have seen the js code it's absolutely fine but one problem is there after registering it's not directing to login page

**Comment by Amit366** [comment]
@ShivamAgarwal-code yes for that there is another issue opened

**Comment by ShivamAgarwal-code** [comment]
I couldn't find that folder is it in github?
![image](https://user-images.githubusercontent.com/72163800/152499661-4f842f9b-b436-4bcd-bbbf-b71b37f4319c.png)

**Comment by Amit366** [comment]
Inside components folder @ShivamAgarwal-code

**Comment by ShivamAgarwal-code** [comment]
Can you send the folder here..
