### ISSUE TITLE
Enhancement in the UI of the Signup and Login pages

### ISSUE THREAD

**Issue by souravseal99** [Tech-N-Science/FunwithScience#328]
**Is your feature request related to a problem? Please describe.**
it's not related to any problem, it's simply an enhancement request.

**Describe the solution you'd like**
I have tried designing something new for the Sign-up and login pages.  

# Before 

### Signup page 
![image](https://user-images.githubusercontent.com/69809086/150630552-15ff5d54-2241-48ef-9e0a-6bf52d8225a7.png)

### Login page 
![image](https://user-images.githubusercontent.com/69809086/150630571-9088748c-2c07-4952-bf7b-123ecf70e63d.png)

# After 
### SignUp page 
![Desktop - 1](https://user-images.githubusercontent.com/69809086/150630618-53a0debe-5c1d-4068-a6ac-9726957992e0.png)

### Login page
![Desktop - 2](https://user-images.githubusercontent.com/69809086/150630623-b87e5878-78db-4668-b8db-8b208ec14956.png)

**Comment by Amit366** [comment]
@souravseal99 hello, nice to see u back. Can u send the pic of mobile view?

**Comment by SayanDeveloper** [comment]
But does this UI look better?

**Comment by Amit366** [comment]
Let's do one thing, let's ask it on LinkedIn 😁.

**Comment by souravseal99** [comment]
> @souravseal99 hello, nice to see u back. Can u send the pic of mobile view?

Hi @Amit366, Glad to know that...😃. 

Sure...! I'll be making one for the mobile view.

**Comment by souravseal99** [comment]
😸 besides, If you guys have anything specific in mind, please feel free to reach out to me in the discord group.
@Amit366, @SayanDeveloper 

> Let's do one thing, let's ask it on LinkedIn 😁.

**Comment by souravseal99** [comment]
here are the designs for the mobile view @Amit366.

### Design 1
![Android Small - 2](https://user-images.githubusercontent.com/69809086/150970599-51edeb6e-fbd7-455f-a160-2b84b884a533.png)

### Design 2
![Android Small - 1](https://user-images.githubusercontent.com/69809086/150970632-8f109813-eeca-4ab2-ab0a-96cb957fba33.png)

### Design 3
![Android Small - 1](https://user-images.githubusercontent.com/69809086/150972907-7b09ad6e-3220-44be-ae7a-6e2c7f45848e.png)

### Design 4
![Android Small - 1 (1)](https://user-images.githubusercontent.com/69809086/150972940-a6c5141f-723d-40d0-a4f8-65065b25f81e.png)

**Comment by prakhar-161** [comment]
Hey, can i work on this issue? Will try to improve the css of the borders and the text regions.

**Comment by Amit366** [comment]
@SayanDeveloper @souravseal99 let's see which UI is better. 
https://www.linkedin.com/posts/amit-kumar-mishra-28122a193_uiux-activity-6891990128592609280-NDkY

**Comment by souravseal99** [comment]
> I think if the border radius would be a little bit lesser then it would look great with a play of shadow

something like this ? 

![Android Small - 2](https://user-images.githubusercontent.com/69809086/151170536-aeb85058-c1d3-4c65-8a0a-af662c1cb566.png)

![Android Small - 1](https://user-images.githubusercontent.com/69809086/151170545-4ba4f1c9-f224-48b3-984d-cc602dfaa9b5.png)

**Comment by Amit366** [comment]
@souravseal99 u can send the PR.

**Comment by souravseal99** [comment]
> @souravseal99 u can send the PR.

@Amit366 what will be the design for the mobile view ?

**Comment by souravseal99** [comment]
> This one @souravseal99

Thanks @Amit366

**Comment by whiteHatpro** [comment]
i want to work in this issue under JWOC
