### ISSUE TITLE
Change the font style of the formulas in the calculators

### ISSUE THREAD

**Issue by Amit366** [Tech-N-Science/FunwithScience#329]
Change the font style of the formulas in the calculators. Now it is cursive which is not properly understandable in mobile view. So change it to some font which is understandable and also different from the rest font.

**Comment by varunwho** [comment]
@Amit366 Can I work on this?

**Comment by Kaggrov** [comment]
I want to work on this issue under JWOC

**Comment by whiteHatpro** [comment]
I want to work on this issue under JWOC

**Comment by VaishnaviNigam25** [comment]
I want to work on this issue under JWOC @Amit366

**Comment by Amit366** [comment]
@varunwho are u interested in working?

**Comment by varunwho** [comment]
> @varunwho are u interested in working?

Yess
