### ISSUE TITLE
Change UI of math calculator

### ISSUE THREAD

**Issue by Amit366** [Tech-N-Science/FunwithScience#330]
**Is your feature request related to a problem? Please describe.**
Change UI of math calculator

**Describe the solution you'd like**
In math calculators the example is written under process section, but change UI such that the example is separated

**Comment by varunwho** [comment]
@Amit366 can I try working on this?

**Comment by Amit366** [comment]
@varunwho r u interested in working?

**Comment by varunwho** [comment]
> @varunwho r u interested in working?

Yess

**Comment by Amit366** [comment]
@varunwho u need to send the PR today

**Comment by varunwho** [comment]
I'm actually stuck up with some urgent work so I'm unassigning myself. Sorry!
And thanks for the chance!

**Comment by 03amir** [comment]
I want to work on this issue under JWOC
