### ISSUE TITLE
statistics formula table

### ISSUE THREAD

**Issue by Amit366** [Tech-N-Science/FunwithScience#331]
**Is your feature request related to a problem? Please describe.**
In statistics calculator the table must be designed similar to other calculators.

**Comment by Kaggrov** [comment]
I want to work on this issue under JWOC

**Comment by raxvab** [comment]
I want to work on this issue under JWOC it's gonna be one of the first opportunities for me to start with open source can i get this issue assigned.

**Comment by Amit366** [comment]
@Kaggrov r u interested in working?

**Comment by Kaggrov** [comment]
Yes sir
