### ISSUE TITLE
Button formatting and small bugs

### ISSUE THREAD

**Issue by Geeky-Sam01** [Tech-N-Science/FunwithScience#332]
**Is your feature request related to a problem? Please describe.**

1) The buttons of the calculators need to be centered in mobile view
2) on clicking the logo, user must be redirected to home page
3) change the plus button of the physics, math and chemistry cards to "explore" with a symbol.

**Comment by ShaileshKumar007** [comment]
Hii @Geeky-Sam01 
Just want to say that instead of writing the whole issue in the title, you should write your issue inside the template that is being provided by maintainers so that it'll be easy for maintainers also to look at this issue.

**Comment by KushalGhosh9899** [comment]
I want to work on this issue under JWOC @Amit366

**Comment by KushalGhosh9899** [comment]
I want to work on this issue under JWOC @Amit366

**Comment by Amit366** [comment]
@Geeky-Sam01 r u working?

**Comment by Priiyaa** [comment]
Hi ! If this issue is not assigned to anyone yet then I would love to work on it!

**Comment by Geeky-Sam01** [comment]
> @Geeky-Sam01 r u working?

Yes

**Comment by Geeky-Sam01** [comment]
> Hii @Geeky-Sam01 Just want to say that instead of writing the whole issue in the title, you should write your issue inside the template that is being provided by maintainers so that it'll be easy for maintainers also to look at this issue.

Creating a new Issue then.

**Comment by Amit366** [comment]
@Geeky-Sam01 u need to submit it by tomorrow. As for medium issue, only 2 days u will get.

**Comment by Amit366** [comment]
> > Hii @Geeky-Sam01 Just want to say that instead of writing the whole issue in the title, you should write your issue inside the template that is being provided by maintainers so that it'll be easy for maintainers also to look at this issue.
> 
> Creating a new Issue then.

No need work on this

**Comment by Geeky-Sam01** [comment]
Sorry, cannot do it. Please assign it to someone else.

**Comment by Amit366** [comment]
@KushalGhosh9899 are u interested in this issue?

**Comment by Amit366** [comment]
@Priiyaa r u interested in working?

**Comment by KushalGhosh9899** [comment]
Yes Please assign this to me, I want to work on this issue under JWOC @Amit366

**Comment by Amit366** [comment]
@KushalGhosh9899 send ur previous issue by tomorrow
