### ISSUE TITLE
Side Navbar Required

### ISSUE THREAD

**Issue by pranavsuriya-sr** [Tech-N-Science/FunwithScience#333]
**Is your feature request related to a problem? Please describe.**
Adding a navigation bar in the right side would be good for easy navigation through the webpage. If in case when the webpage is developed and new content is being added, the length of the whole site increases and so scrolling throughout the page wouldn't be good.  So a side navbar is surely required.

**Comment by Sanket1308** [comment]
I want to work on this issue under JWOC

**Comment by Amit366** [comment]
I don't think this feature is required for time being. We could add it in future if needed.
