### ISSUE TITLE
FAQs should be at the center 

### ISSUE THREAD

**Issue by kunalahuja06** [Tech-N-Science/FunwithScience#338]
**Describe the bug**
Each of the FAQs is slightly at the top of the container.

**To Reproduce**
1. Go to 'FunwithScience/funwithphysics/src/Components/FAQ/Faq.css'
2. Click on 'Faq.css'
3. Scroll down to '.faq-heading'

**Expected behavior**
Each question should be center-aligned.

**Screenshots**
![2022-01-30_LI](https://user-images.githubusercontent.com/52367650/151704901-f68fcc22-bcc5-407a-bb0d-cc2bf8ac2d3c.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave browser
 - Version: 1.34.81

**Smartphone (please complete the following information):**

**Additional context**

**Comment by KushalGhosh9899** [comment]
Hi @kunalahuja06, Is anyone is working on this issue?

**Comment by kunalahuja06** [comment]
> Hi @kunalahuja06, Is anyone is working on this issue?

Nope, ask any one of the contributors to assign this issue to you...

**Comment by KushalGhosh9899** [comment]
@Amit366 Kindly allot this issue to me whenever it's possible.
