### ISSUE TITLE
Some pages appear from the middle

### ISSUE THREAD

**Issue by Amit366** [Tech-N-Science/FunwithScience#339]
**Describe the bug**
There are some pages which appear from the middle and not from the start. So fix the bug such that all the pages appear from the start.

**Comment by raxvab** [comment]
I want to work on this issue under JWOC it's gonna be one of the first opportunities for me to start with open source can i get this issue assigned.

**Comment by Amit366** [comment]
@raxvab go ahead

**Comment by raxvab** [comment]
what's the deadline ?

**Comment by Amit366** [comment]
@raxvab tomorrow
