### ISSUE TITLE
On signing up the user should be directed to login page

### ISSUE THREAD

**Issue by Amit366** [Tech-N-Science/FunwithScience#340]
**Describe the bug**
On signing up, an alert appears and on clicking 'ok' it should be redirected to login page.

**Comment by manya0210** [comment]
Hey!!! I want to work under JWOC.

**Comment by Amit366** [comment]
@manya0210 u can work

**Comment by ATUL6026** [comment]
I want to work on this issue under JWOC.

**Comment by Amit366** [comment]
@tanya-gupta25 r u not interested in this issue?

**Comment by tanya-gupta25** [comment]
> @tanya-gupta25 r u not interested in this issue?

Actually I am new to React so I am unable to do it , u can assign it to someone else . Thankyou.

**Comment by dhruvtongia** [comment]
I want to work on this issue under JWOC.
