### ISSUE TITLE
On login the user should be directed to home page.

### ISSUE THREAD

**Issue by Amit366** [Tech-N-Science/FunwithScience#341]
**Describe the bug**
On login, an alert message appears and when the user clicks 'ok' he should be directed to home page

**Comment by sahilkr9** [comment]
Can I claim this issue?

**Comment by ShrutiKapure** [comment]
I want to work on this issue under **JWOC**.

**Comment by raxvab** [comment]
I want to work on this issue under JWOC it's gonna be one of the first opportunities for me to start with open source can i get this issue assigned.

**Comment by Amit366** [comment]
@sahilkr9 r u interested?

**Comment by sahilkr9** [comment]
> @sahilkr9 r u interested?

I have already been assigned another issue. Please assign this one to another mentee. Thank you for the opportunity.

**Comment by Amit366** [comment]
@ShrutiKapure r u interested?

**Comment by Arun5023** [comment]
I want to work on this issue under JWOC

**Comment by tanya-gupta25** [comment]
I want to work on this issue under JWOC.

**Comment by amanbedi1** [comment]
can you assign this issue to me

**Comment by dhruvtongia** [comment]
I want to work on this issue under JWOC.

**Comment by Amit366** [comment]
@amanbedi1 since u haven't finished it yet so I am unassigning u.

**Comment by Amit366** [comment]
@dhruvtongia it would be nice if u could star the repo
