### ISSUE TITLE
Add image loading feature to the contact us image

### ISSUE THREAD

**Issue by Amit366** [Tech-N-Science/FunwithScience#342]
**Is your feature request related to a problem? Please describe.**
When the website is loading the contact us image doesn't appear instantly, on fully loading then it appears.

**Describe the solution you'd like**
Make it similar to the sign up and login page images.

**Comment by SabariGanesh-K** [comment]
@Amit366 Its already there right ?!

**Comment by Amit366** [comment]
@SabariGanesh-K it's there for login and sign up but not for contact us
