### ISSUE TITLE
Add a timer to the quiz page

### ISSUE THREAD

**Issue by Amit366** [Tech-N-Science/FunwithScience#344]
**Is your feature request related to a problem? Please describe.**
Add a smaller timer at the top of the quiz page and also make it responsive

**Comment by raxvab** [comment]
I want to work on this issue under JWOC it's gonna be one of the first opportunities for me to start with open source can i get this issue assigned.

**Comment by Shruti025** [comment]
hey, I would love to work on this issue under JWOC

**Comment by 03amir** [comment]
I want to work on this issue under JWOC.

**Comment by Amit366** [comment]
@03amir u can work on this issue, but make the timer to the left corner and also don't display the timer at the score page.

**Comment by raxvab** [comment]
Hello @Amit366 can can I add my name to the contributor list ?

**Comment by Amit366** [comment]
@raxvab already added

**Comment by raxvab** [comment]
Thanks @Amit366

**Comment by Amit366** [comment]
@03amir this issue also u haven't sent any PR

**Comment by 03amir** [comment]
I will.
