### ISSUE TITLE
Add questions page in math section

### ISSUE THREAD

**Issue by Amit366** [Tech-N-Science/FunwithScience#345]
**Is your feature request related to a problem? Please describe.**
Add questions page in math section

**Describe the solution you'd like**
Make the question page similar to the physics question page.

**Comment by Kaggrov** [comment]
I would like to work on this issue under JWOC

**Comment by Amit366** [comment]
@Kaggrov what's the update?

**Comment by Kaggrov** [comment]
Yeah I have done a part of problem and working on another part.

**Comment by Amit366** [comment]
@Kaggrov see u need to just copy the same format as Physics ,nothing new things to be added.
