### ISSUE TITLE
Add complex number calculator

### ISSUE THREAD

**Issue by Amit366** [Tech-N-Science/FunwithScience#346]
**Is your feature request related to a problem? Please describe.**
Add complex number calculator

**Describe the solution you'd like**
Add complex number calculator in algebra section and also add formula table as done in geometry calculators

**Comment by KushalGhosh9899** [comment]
In this we just have to implement calculations which will be done on backend and the respective result will be displayed on the result box because front end is already there? We just have to add backend calculations right @Amit366 ?
If this is the case then please assigned this to me.

**Comment by KushalGhosh9899** [comment]
Do we have to implement these following subtopic under complex number calculator :-
> Algebra of Complex Numbers
> The Modulus and the Conjugate of a Complex Numbers
> Argand Plane and Polar Representation
Please let me know @Amit366

**Comment by KushalGhosh9899** [comment]
I want to work on this issue under JWOC
