### ISSUE TITLE
Calculator for quadratic equation

### ISSUE THREAD

**Issue by Amit366** [Tech-N-Science/FunwithScience#357]
**Is your feature request related to a problem? Please describe.**
Calculator for quadratic equation

**Describe the solution you'd like**
Add the quadratic equation to algebra section

**Comment by Tess-Vanta** [comment]
I would like to take up this issue under JWOC

**Comment by Tess-Vanta** [comment]
hey sorry, i wouldnt we able to finish. Could you unassign me?

**Comment by Amit366** [comment]
@SaarthakMaini u understood it correctly. And also u need to add it in algebra folder

**Comment by SaarthakMaini** [comment]
Thank you very much!!

**Comment by Amit366** [comment]
@SaarthakMaini u need to send the PR today

**Comment by SaarthakMaini** [comment]
Yes, working on it! Thank you for your patience!

**Comment by Amit366** [comment]
@SaarthakMaini today if anyone comments on this issue then I will be assigning them.

**Comment by SaarthakMaini** [comment]
@Amit366 Yes, I understand. Thank you for your time!!

**Comment by Amit366** [comment]
@SaarthakMaini since I received no PR so I am unassigning u.

**Comment by dhruvtongia** [comment]
I want to work on this issue under JWOC

**Comment by Amit366** [comment]
@dhruvtongia u need to send the Pull request within 3 days.
