### ISSUE TITLE
Fix the navbar and scrolling

### ISSUE THREAD

**Issue by Amit366** [Tech-N-Science/FunwithScience#358]
**Describe the bug**
fix the navbar at the top

While scrolling the navbar must be fixed at the top and also there is bug in home page that is when the plus sign on  cards are hovered then within some seconds the page is automatically scrolled to top.

**Comment by Amit91848** [comment]
Can i work on this?

**Comment by Amit91848** [comment]
I fixed the navbar at the top. I tried hovering the plus buttons but for me it wasn't scrolling to the top. I looked at the code and it looks fine to me. If you could tell exactly how it is happening then I will look into it. Should I create a PR for navbar only?

**Comment by Amit366** [comment]
Don't send the PR for navbar only @Amit91848

**Comment by Amit91848** [comment]
I couldn't find any bug for the scrolling problem

**Comment by Amit91848** [comment]
I have some other work won't be able to do it. Can you please un-assign me. Thanks

**Comment by SabariGanesh-K** [comment]
Assign it to me :) @Amit366
