### ISSUE TITLE
Make a separate CSS file

### ISSUE THREAD

**Issue by Amit366** [Tech-N-Science/FunwithScience#371]
**Is your feature request related to a problem? Please describe.**

For all the physics calculators there is a separate CSS file but there are many cross links due to same class names and so make a single CSS file and link it to all the js files of the calculators.

**Comment by Shresa** [comment]
I want to work on this issue under JWOC

**Comment by Amit366** [comment]
@Shresa u need to send the PR by tomorrow

**Comment by tanya-gupta25** [comment]
I want to work on this issue under JWOC

**Comment by Amit366** [comment]
@tanya-gupta25 first send the PR of the issue u r working on and then I will assign it to u.
