### ISSUE TITLE
Adding standard deviation and Variance 

### ISSUE THREAD

**Issue by SabariGanesh-K** [Tech-N-Science/FunwithScience#378]
**Is your feature request related to a problem? Please describe.**
A lot of useful stats are present under this category. But I would add two of the most important stat , standard deviation and variance.

**Describe the solution you'd like**
I would add a corner under results which would show standard deviation and variance

**Comment by Amit366** [comment]
@SabariGanesh-K u will add it in statistics calculators itself right?

**Comment by Amit366** [comment]
Ok
