### ISSUE TITLE
Power function in Algebra Section

### ISSUE THREAD

**Issue by VATSAL-IIT** [Tech-N-Science/FunwithScience#388]
A feature for finding x to the power y in the algebra section

**Comment by VATSAL-IIT** [comment]
I want to work on this under JWOC

**Comment by Amit366** [comment]
@VATSAL-IIT This is too small calculator. If u want u can combine it with square root and cube root in the form of drop down menu. For drop down u can refer to circular motion calculator. And one more thing if u want to work then the definition for each should not be copied from other website, instead add somesome of ur own words.

**Comment by VATSAL-IIT** [comment]
I have seen the refernce and would add dropdown for square-root calculation and cube-root as well .
