### ISSUE TITLE
Create an About page

### ISSUE THREAD

**Issue by ronitblenz** [Tech-N-Science/FunwithScience#389]
I saw that the live deployment has the home page and the about page to be the same
Can you assign me so that I can create an about page for this project?

**Comment by Amit366** [comment]
@ronitblenz can U write the content of about us page?

**Comment by ronitblenz** [comment]
Yeah sure
It will take 2-3 days time, as a medium issue

**Comment by Amit366** [comment]
@ronitblenz see don't create a new page but add it above the learn heading and write some good content which is not copied.

**Comment by ronitblenz** [comment]
Sure

**Comment by ronitblenz** [comment]
I am sorry, I thought it to be a HTML, CSS change
But I am not familiar with React
So, I couldnt contribute to the Project. 

I deeply apologise for this
I am unassigning myself, Hope a better candidate approaches the issue
Thanks

**Comment by Aniket-508** [comment]
@Amit366 I want to work on this issue under JWoC.

**Comment by Amit366** [comment]
@Aniket-508 yes u can.

**Comment by Amit366** [comment]
> @ronitblenz see don't create a new page but add it above the learn heading and write some good content which is not copied.

@Aniket-508

**Comment by Amit366** [comment]
@Aniket-508 any update?

**Comment by r3yc0n1c** [comment]
I want to work on this issue under JWoC'22

**Comment by aditiitomar** [comment]
Hey, @Amit366 I'm a GSSOC participant. Can I work on this?

**Comment by Amit366** [comment]
> @ronitblenz see don't create a new page but add it above the learn heading and write some good content which is not copied.

@aditiitomar you need to do this and also add the link of about us in navbar and footer

**Comment by aditiitomar** [comment]
Hey Amit,
I have few questions related to the issue.
1. How much time limit do I have to solve this issue?
2. I have written the content of About Page, just check if it is okay or
not.

Tech-N-Science was created to help users with calculations for different
science formula. There are many calculators present which helps user
calculate & shows result using formula. Apart from that, we also have a
'questions section' where you can apply filters, difficulty wise & topic
wise, which make it more easy for you to practice. We also have quizz that
gives you a score on the basis of your performance which adds more fun in
learning. Let us together learn a deeper knowledge of science!


Let me know if you want to add/delete something.

**Comment by Amit366** [comment]
@aditiitomar have u created a new page for about us?

**Comment by Ashish4321-hub** [comment]
@Amit366 I'm gssoc contributor and I want to work on about page.Please assign me this issue.

**Comment by aditiitomar** [comment]
@Amit366 I'm working on it.

**Comment by Amit366** [comment]
@Ashish4321-hub u can work

**Comment by Ashish4321-hub** [comment]
@Amit366 i started work on it

**Comment by Amit366** [comment]
> @ronitblenz see don't create a new page but add it above the learn heading and write some good content which is not copied.

@Ashish4321-hub

**Comment by VIDHI-BAJAJ** [comment]
Can I Solve this issue

**Comment by Amit366** [comment]
@VIDHI-BAJAJ yes u can work. but go through the above chats first and do accordingly

**Comment by Amit366** [comment]
@VIDHI-BAJAJ r u working?

**Comment by VIDHI-BAJAJ** [comment]
@Amit366 Yes I am Working On it by 31 st I i will completed

**Comment by VIDHI-BAJAJ** [comment]
@Amit366 Where can I find Heading page

**Comment by navyasharma0203** [comment]
@Amit366 Can I work on this??

**Comment by Amit366** [comment]
> @ronitblenz see don't create a new page but add it above the learn heading and write some good content which is not copied.

@navyasharma0203 u need to follow this.

**Comment by Urstrulysuvangi** [comment]
Hey, I'd like to work on this. Can you please provide me with a little more detail about this?

**Comment by Amit366** [comment]
@Urstrulysuvangi don't create another page for about us. Instead add some content just below the background image. U can also add a good image as well.

**Comment by Urstrulysuvangi** [comment]
> @Urstrulysuvangi don't create another page for about us. Instead add some content just below the background image. U can also add a good image as well. You can refer pull request #414 for the same but need to change the image and modify the content

Okay, thanks a lot. It will take me around 2-3 days, will that be okay with you?

**Comment by Amit366** [comment]
@Urstrulysuvangi ok
