### ISSUE TITLE
Improve Footer

### ISSUE THREAD

**Issue by whiteHatpro** [Tech-N-Science/FunwithScience#392]
The footer seems to be a bit up and not the text alignment seems to be improper
allover i want to give footer a good and responsive look.

**Comment by whiteHatpro** [comment]
I want to work on this issue under JWoC

**Comment by ItsRoy69** [comment]
I want to work on this issue under JWoC

**Comment by Amit366** [comment]
@whiteHatpro footer is fine no need to do any changes but if u want u can add the footer to algebra topics page. If u want to work I will assign u

**Comment by Amit366** [comment]
@ishitaac can u work on this?

> @whiteHatpro footer is fine no need to do any changes but if u want u can add the footer to algebra topics page. If u want to work I will assign u

**Comment by sayan404** [comment]
I want to work in this issue under JWOC. @Amit366

**Comment by ishitaac** [comment]
> @ishitaac can u work on this?
> 
> > @whiteHatpro footer is fine no need to do any changes but if u want u can add the footer to algebra topics page. If u want to work I will assign u

yes i can

**Comment by ishitaac** [comment]
Pls assign me @Amit366

**Comment by Amit366** [comment]
@ishitaac u can work

**Comment by LakshayN** [comment]
@Amit366 i can improve the footer, can you assign this to me ?

**Comment by Amit366** [comment]
@ishitaac update?

**Comment by Amit366** [comment]
@LakshayN u can work

**Comment by Amit366** [comment]
> @whiteHatpro footer is fine no need to do any changes but if u want u can add the footer to algebra topics page. If u want to work I will assign u

@LakshayN but u need to do this

**Comment by Ishhha** [comment]
I want to work on the issue. Please assign it to me.

**Comment by Amit366** [comment]
@Ishhha r u a part of any open source?

**Comment by Ishhha** [comment]
I'm a contributor in GSSOC'22.

**Comment by Amit366** [comment]
@Ishhha go ahead

**Comment by rohitkhicher001** [comment]
I am a gssoc22 contributer. I would like to work on this.

**Comment by Amit366** [comment]
@rohitkhicher001 add the footer to algebra topics pages. and don't change anything
