### ISSUE TITLE
Bug: Permutaion and Combination components

### ISSUE THREAD

**Issue by VATSAL-IIT** [Tech-N-Science/FunwithScience#393]
When the value of n is greater than r, the permutation and combination component should give an error. Also, can it be merged into a single section with a dropdown feature as is in the case of Circular Motion Calculator? That would be better according to me.

**Comment by VATSAL-IIT** [comment]
i want to work on this issue under JWOC

**Comment by Amit366** [comment]
@VATSAL-IIT u need to add proper example for each of permutation and combination and also add the definition and process as it is.

**Comment by VATSAL-IIT** [comment]
ya sure will do that
