### ISSUE TITLE
Add Binomial theorem calculator

### ISSUE THREAD

**Issue by Amit366** [Tech-N-Science/FunwithScience#399]
**Is your feature request related to a problem? Please describe.**
Add the Binomial theorem calculator in the algebra section.
The definition should be unique means u can see the definition from other websites but do not copy it directly. And also add the formulas list at the end of the calculator.

The calculator must be binomial expansion

**Comment by Trisha-tech** [comment]
Hi @Amit366, I want to work on this issue under JWoC.

**Comment by Amit366** [comment]
Ok

**Comment by Amit366** [comment]
@Trisha-tech update?

**Comment by VATSAL-IIT** [comment]
I want to work on this issue under JWOC.
