### ISSUE TITLE
Spherical surface Refraction  calculator for Photonics section

### ISSUE THREAD

**Issue by VATSAL-IIT** [Tech-N-Science/FunwithScience#446]
A calculator for dealing with reflection as well as refraction in between two general surfaces (not specifically lens or mirror) .This will be applicable to any 2 general spherical surfaces.

**Comment by VATSAL-IIT** [comment]
I want to work on this issue under JWOC

**Comment by Amit366** [comment]
@VATSAL-IIT any update?

**Comment by VATSAL-IIT** [comment]
ya its almost done , will make PR by tonight
