### ISSUE TITLE
**When click on trigonometry calculator redirect to the home page** 

### ISSUE THREAD

**Issue by yaman-694** [Tech-N-Science/FunwithScience#449]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yaman-694** [comment]
i can add trigonometry calculator assign this issue to me

**Comment by Priyanshu174** [comment]
Do we have to add trigonometry calculator or it's already added but not going to that page after clicking? If latter one is the issue then I can work on this issue.

**Comment by Amit366** [comment]
This issue is already resolved.
