### ISSUE TITLE
**Make better looking Navbar** align items in navbar

### ISSUE THREAD

**Issue by yaman-694** [Tech-N-Science/FunwithScience#450]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yaman-694** [comment]
I want to work on the front-end part of the website 
I want to make navbar look more better assign me this issue please

**Comment by riiyaaa** [comment]
I would like to work on it under JWOC

**Comment by Amit366** [comment]
@yaman-694 can u tell me or send any image of how u would like to make the navbar?

**Comment by anish2210** [comment]
hello friends, I want to work on this issue can anyone please assign this work to me I am attaching one of my works with this comment, It is a registration/login page that is built on stackblitz.
MUST CHECK THE RESPONSIVENESS 😊
link - https://angular-ivy-iro2sa.stackblitz.io

**Comment by yaman-694** [comment]
This is your current navbar 
![image](https://user-images.githubusercontent.com/72979343/156131253-ae50590f-afa8-4026-a0ba-77e0b580325b.png)

and i want align the list and change font style of tech n science
i tried this if you assign me i will on this more
![image](https://user-images.githubusercontent.com/72979343/156131494-16116b92-afc9-47bd-a235-8e7643f04907.png)

**Comment by yaman-694** [comment]
I have some idea with home page too

**Comment by Amit366** [comment]
Ok go ahead

**Comment by AnIkeT126** [comment]
Can i contribute in it as a part of GSSoC'22?

**Comment by Amit366** [comment]
@AnIkeT126 it's already assigned

**Comment by bhumithakur** [comment]
If it's not done yet, can i contribute to it?

**Comment by yaman-694** [comment]
i made pull request already

**Comment by yaman-694** [comment]
close this issue pull request merged
