### ISSUE TITLE
to create the steps solutions and calculator for the topics of Quantum mechanics(Atomic Physics)  and Thermodynamics.

### ISSUE THREAD

**Issue by Smriti-y** [Tech-N-Science/FunwithScience#453]
**add the step  solutions and calculator for the topic under Quantum Mechanics and Thermodynamics**
(a)The topics under Quantum mechanics  which I will add is as follows-
1)Heisenberg's Uncertainity Principle Calculator(+theory of the principle) 
(b)Thermodynamics -
1)Newton's law of cooling Calculator and its theory (with step by step solutions)

**Comment by Amit366** [comment]
@Smriti-y impulse is already present under collision, kinetic energy is present under work power energy.
If u want u can work on other two calculators.

**Comment by Smriti-y** [comment]
Sir,can I edit my issue ??

**Comment by Amit366** [comment]
Yes

**Comment by sharma-tanishq** [comment]
Hi I am a GSSOC22 contributer can i work on this?
