### ISSUE TITLE
Bugs in physics Quiz

### ISSUE THREAD

**Issue by VATSAL-IIT** [Tech-N-Science/FunwithScience#459]
In the physics quiz section,while giving the quiz, if a person checks an option more than once the score gets added more than once which shouldn't occur. Also if I click a wrong option  and then I immediately check the correct option the score gets incremented which is also a bug.

**Comment by VATSAL-IIT** [comment]
I want to work on this issue under JWOC

**Comment by Amit366** [comment]
@VATSAL-IIT go ahead
