### ISSUE TITLE
Add steps for circular motion calculator

### ISSUE THREAD

**Issue by Amit366** [Tech-N-Science/FunwithScience#460]
**Is your feature request related to a problem? Please describe.**
Add steps for circular motion calculator in classical mechanics calculator, means on clicking calculator entire steps should appear. For reference u can check collision calculator.

**Comment by debjitpurohit** [comment]
assign me this task

**Comment by Amit366** [comment]
@debjitpurohit go ahead

**Comment by debjitpurohit** [comment]
thank you sir

**Comment by lakshrav** [comment]
Heyy if this issue is available, could you please assign it to me?

**Comment by Amit366** [comment]
@lakshrav yes

**Comment by lakshrav** [comment]
Thank you
