### ISSUE TITLE
Add steps for statistics calculator 

### ISSUE THREAD

**Issue by Amit366** [Tech-N-Science/FunwithScience#461]
**Is your feature request related to a problem? Please describe.**
Add steps for statistics calculator in algebra section, means on clicking calculator entire steps should appear. For reference u can refer the physics calculators

**Comment by LakshayN** [comment]
@Amit366 I can add steps for statistics calculator in algebra section. I want to work for this under GSSoC22

**Comment by Amit366** [comment]
@LakshayN ok

**Comment by Aditya3403** [comment]
I would like to work on this issue . Kindly assign this issue to me.

**Comment by ankitadam** [comment]
@Amit366 I would like to work on this issue. Please assign it to me.

**Comment by Amit366** [comment]
@ankitadam u can work

**Comment by ankitadam** [comment]
Sorry, I won't be able to work on it so I removed my assignment.

**Comment by Sukriti-m** [comment]
Hey @Amit366. I would like to work on this issue.
 I'd be grateful if you could assign this task to me under GSSOC'22.

**Comment by Sukriti-m** [comment]
Hey @Amit366. 
I would like to work on this issue. I'd be grateful if you could assign this task to me under GSSOC'22.

**Comment by Amit366** [comment]
@Sukriti-m u can work
