### ISSUE TITLE
Add steps for progression calculator 

### ISSUE THREAD

**Issue by Amit366** [Tech-N-Science/FunwithScience#462]
**Is your feature request related to a problem? Please describe.**
Add steps for statistics calculator in algebra section, means on clicking calculator entire steps should appear. For reference refer physics calculator

**Comment by Aditya3403** [comment]
I would like to work on this issue. Kindly assign this issue to me.

**Comment by Amit366** [comment]
See on clicking the calculate button of calculator then it should show the steps or error message. Thats why ser the physics calculator collision

**Comment by Aditya3403** [comment]
Sir I have forked the repo in my local system but I am unable to find the file I have to work upon. Kindly guide me for the same.

**Comment by Amit366** [comment]
@KushalGhosh9899 u can work
