### ISSUE TITLE
Add Steps to Density Calculator in Fluid Mechanics.

### ISSUE THREAD

**Issue by AnuragParashar2000** [Tech-N-Science/FunwithScience#463]
Add steps for Fluid Mechanics calculator in Classical Mechanics section. For reference, u can refer to the physics calculators

**Comment by ridhig16** [comment]
I am a GSSOC'22 participant and want to work on this issue. Pls assign this issue to me

**Comment by Amit366** [comment]
@ridhig16 go ahead

**Comment by AnIkeT126** [comment]
I am a GSSOC'22 participant and want to work on this issue under the same.

**Comment by Sukriti-m** [comment]
Hey @Amit366
I would like to work on this issue. I'd be grateful if you could assign this task to me under GSSOC'22.

**Comment by RishikaKant** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by Amit366** [comment]
@RishikaKant first remove the bug from ur previous PR and then u can work on this

**Comment by singhnaveen098** [comment]
@Amit366 I would like to work on this issue. Please assign it to me.

**Comment by Amit366** [comment]
@singhnaveen098 u can work

**Comment by RishikaKant** [comment]
Okay!
