### ISSUE TITLE
add to  feature  science formula

### ISSUE THREAD

**Issue by Khushbu-kumari-87090** [Tech-N-Science/FunwithScience#465]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Khushbu-kumari-87090** [comment]
some formula is so much tough so    this feature  will provide  so easy for understanding purpose.

**Comment by Khushbu-kumari-87090** [comment]
i mean  some project  will  describe you are going to incorrect way so please try again.

**Comment by Amit366** [comment]
For that already on clicking calculate we get that error message

**Comment by Khushbu-kumari-87090** [comment]
calculate so we get the error so that project will describe the digit number and some string character.

**Comment by Khushbu-kumari-87090** [comment]
and using some fonts

**Comment by Khushbu-kumari-87090** [comment]
so please assign me.

**Comment by Amit366** [comment]
@Khushbu-kumari-87090 ok try and also further discussion can be done over discord
