### ISSUE TITLE
Adding solutions of quiz and different difficulty level questions

### ISSUE THREAD

**Issue by rohitalal** [Tech-N-Science/FunwithScience#466]
- After answering the questions of the quiz, solution should be given.

- 3 difficulty level of questions should be present - Easy, medium and hard.

- Each difficulty level should have different time limit.

**Comment by Amit366** [comment]
@rohitalal see what exactly I was thinking is, after the quiz then the solution should be present. and as u said different questions will have different time.

**Comment by MnCSSJ4x** [comment]
can I work on this issue
