### ISSUE TITLE
Add questions to Math questions section

### ISSUE THREAD

**Issue by itzwow** [Tech-N-Science/FunwithScience#468]
**Describe the bug**
In the questions section of math the questions and answers are wrong

![issue1](https://user-images.githubusercontent.com/84179065/156196599-500da694-c240-4d20-b5df-2974d81d8a2a.JPG)

There is no correct option according to the question

Moreover the styling part can be done better

**Comment by Amit366** [comment]
@itzwow the math question page is not completely prepared yet. That's just a demo question.

**Comment by Amit366** [comment]
U can check out physics question page for styling.

**Comment by purohitmansi** [comment]
Hello @Amit366!

I am a GSSoC22 contributor. I would love to work on this issue and make PR as soon as I resolve the issue. Please do assign this to me.

ThankYou:)

**Comment by Amit366** [comment]
@itzwow since there is no update then @purohitmansi can work

**Comment by Amit366** [comment]
> @itzwow the math question page is not completely prepared yet. That's just a demo question.

@purohitmansi add some  good quality questions from some standard text books

**Comment by Amit366** [comment]
@RishikaKant u need to add some good questions to maths section and also mention the difficulty level and also topic name. Just refer the physics questions section

**Comment by RishikaKant** [comment]
Sure! Thank you

**Comment by akrati-max** [comment]
hello @Amit366 
i want to add some questions to maths question section. I am a GSSoC22 contributor.please assign this to me.

**Comment by Amit366** [comment]
@akrati-max u can work
