### ISSUE TITLE
add editorial of physics problems.

### ISSUE THREAD

**Issue by shreyasharma0201** [Tech-N-Science/FunwithScience#477]
**Adding solution of problems will add values to the project.**

> * As a user, I won't want to search solution elsewhere. 
> * Add solution to each problem in physics section.
> * Don't worry for accuracy of solution.
> * There will be errorless solutions.
> * Prior to going to editorial, it will ask if the user spent enough time to the question.

*It may also be possible to display some beautiful messages.*

Looking for getting assigned and admins' point of view.

**Comment by shreyasharma0201** [comment]
@Amit366 yes all to questions under physics section.

**Comment by Amit366** [comment]
@shreyasharma0201 go ahead

**Comment by sonalee21** [comment]
Hello,
I would like to work on this, please assign it to me.

**Comment by Amit366** [comment]
@sonalee21 u can work.

**Comment by Amit366** [comment]
U basically need to write the solution of the MCQ or the numerical based questions in the physics section. If u have any doubt then ask me on discord.

**Comment by Amit366** [comment]
@sonalee21 any update?

**Comment by rohitkhicher001** [comment]
I would like to know more about this issue. After clicking on the options in the quiz we will automatically know the solution. So which solution are we talking about?
