### ISSUE TITLE
Binomial Calculator

### ISSUE THREAD

**Issue by AnIkeT126** [Tech-N-Science/FunwithScience#479]
For the expression of type (ax+by)^n, the current binomial calculator has no resource to calculate the value of the expression if x and y are given, so can I try and add that feature as well, so that if a user wants, they can get the utmost resolved result.

Can I work on this issue as a part of GSSoC'22 @Amit366 ??

**Comment by AnIkeT126** [comment]
Hey, so you can create your own issue which is not this and you can start
working on it.
This issue has been assigned to me.

**Comment by AnIkeT126** [comment]
> I would like to work on this issue, can you please assign me? I am a GSSOC'22 participant. Kindly assign me this issue.

Hey, so you can create your own issue which is not this and you can start
working on it.
This issue has been assigned to me

**Comment by Himanshu1808** [comment]
> > I would like to work on this issue, can you please assign me? I am a GSSOC'22 participant. Kindly assign me this issue.
> 
> Hey, so you can create your own issue which is not this and you can start working on it. This issue has been assigned to me

> Okay, thank you

**Comment by maura-dev** [comment]
Is this issue still up for grabs?

**Comment by Amit366** [comment]
@maura-dev yes

**Comment by maura-dev** [comment]
Please assign to me for gssoc
