### ISSUE TITLE
No scrolling down option in homepage 

### ISSUE THREAD

**Issue by aditiitomar** [Tech-N-Science/FunwithScience#482]
**Describe the bug**
There is no scroll bar on the right side of the page.

**Expected behavior**
There must be a scrollbar to move vertically through the page.

**Screenshots**
![NoScrollBar](https://user-images.githubusercontent.com/80448500/156365486-3665eeb2-9422-4a2e-9f2e-d46fb10d8f0f.png)

**Comment by aditiitomar** [comment]
Hey, @Amit366 Can I work on this issue?

**Comment by Amit366** [comment]
@aditiitomar there is no requirement of scrolling bar as of now. And also u can work on the issue assigned to u first.
