### ISSUE TITLE
Add Steps to Pressure Calculator in Fluid Mechanics inside Classical Mechanics.

### ISSUE THREAD

**Issue by AnuragParashar2000** [Tech-N-Science/FunwithScience#483]
Add steps for the Pressure calculator in the Fluid Mechanics section in the Classical Mechanics, means on clicking calculator entire steps should appear. For reference, u can refer to the physics calculators.

**Comment by Manik-Aggarwal** [comment]
I want to work on this issue, please assign it to me

**Comment by Amit366** [comment]
@AnuragParashar2000 please assign the issue to me under GSSOC
