### ISSUE TITLE
Add Steps to Volume flow rate Calculator in Fluid Mechanics inside Classical Mechanics.

### ISSUE THREAD

**Issue by AnuragParashar2000** [Tech-N-Science/FunwithScience#484]
Add steps for the Volume flow rate calculator in the Fluid Mechanics section in the Classical Mechanics, means on clicking calculator entire steps should appear. For reference, u can refer to the physics calculators.

**Comment by sinha-toyeesh** [comment]
I would like to work on this issue please assign it to me.
