### ISSUE TITLE
Add Steps to Continuity equation Calculator in Fluid Mechanics inside Classical Mechanics.

### ISSUE THREAD

**Issue by AnuragParashar2000** [Tech-N-Science/FunwithScience#486]
Add steps for the Continuity equation calculator in the Fluid Mechanics section inside Classical Mechanics, means on clicking calculator entire steps should appear. For reference, u can refer to the physics calculators.

**Comment by Manik-Aggarwal** [comment]
Please assign it to me

**Comment by bhuvan2002** [comment]
Hello, Please assign it to me as I am  GSSOC contributor

**Comment by shahishree03** [comment]
How many members can assign in each issue

**Comment by AnuragParashar2000** [comment]
It is assigned to @Manik-Aggarwal , it cannot be assigned to two people.

**Comment by Amit366** [comment]
@Manik-Aggarwal r u working?

**Comment by Manik-Aggarwal** [comment]
I am working
