### ISSUE TITLE
Extra line at the end under Faqs

### ISSUE THREAD

**Issue by rohinish404** [Tech-N-Science/FunwithScience#492]
**Describe the bug**
An extra line at the end below How to contact us. Its destroying the symmetry.

**Expected behavior**
The extra line should be removed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Additional context**
<img width="1089" alt="Screenshot 2022-03-03 at 9 57 49 AM" src="https://user-images.githubusercontent.com/92542124/156496259-15b857f0-bac5-4b99-89ec-a34ac593fac5.png">

**Comment by Amit366** [comment]
@rohinish404 go ahead

**Comment by rohinish404** [comment]
sure!!

**Comment by rohinish404** [comment]
where can i find the css part of the Faqs??

**Comment by Amit366** [comment]
U can find it inside, fun with physics folder, then components and then faq

**Comment by rohinish404** [comment]
I looked into the faq folder. But im currently a beginner in fronted. i thought this would be some css related issue. but in the faq section javascript and react is also used. so if you can refer me to some resources about how to remove that line , than i can work on it.

**Comment by Amit366** [comment]
@rohinish404 there is no resource particularly relating to this issue. U need to atleast have some knowledge in JavaScript then only it will ve easy for u to learn and work in react.

**Comment by ronitrangwani** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.

**Comment by Amit366** [comment]
@rohinish404 r u working?

**Comment by rohinish404** [comment]
nope...u can unassign me.

**Comment by ronitrangwani** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.

**Comment by ananya2001roy** [comment]
i want to work on this issue

**Comment by krithika2411** [comment]
Hie can you assign me this issue i would like to rectify it

**Comment by purohitmansi** [comment]
Hello @Amit366!

I am a GSSoC22 contributor. I would love to work on this issue and make PR as soon as I resolve the issue. Please do assign this to me.

ThankYou:)

**Comment by Amit366** [comment]
@krithika2411 do u want to work?

**Comment by krithika2411** [comment]
@Amit366  yes i would like to go for it

**Comment by Tiya0310** [comment]
is this issue up for grab?

**Comment by dvlsatya** [comment]
I am a GSSoC22 contributor. I would love to work on this issue and make PR as soon as I resolve the issue. Please do assign this to me.

**Comment by krithika2411** [comment]
@Amit366  kindly assign this this to me

**Comment by Amit366** [comment]
@krithika2411 u can work

**Comment by krithika2411** [comment]
@Amit366  kindly assign this to me i will done with the change . have to send the pr

**Comment by the-illuminatus** [comment]
can i work on this issue under gssoc22?

**Comment by Amit366** [comment]
@the-illuminatus u can work. Just make sure to give proper padding

**Comment by SHRUTI-SINGH16** [comment]
I would like to work on this issue . Please assign me as a GSSOC 2022 Contributor.

**Comment by Amit366** [comment]
@SHRUTI-SINGH16 u can work

**Comment by its-ayush-07** [comment]
Hello, can I work on this issue under SSOC?

**Comment by its-ayush-07** [comment]
> Hello, can I work on this issue under SSOC?

@Amit366

**Comment by Amit366** [comment]
@its-ayush-07 u can work
