### ISSUE TITLE
Mathematical induction calculator

### ISSUE THREAD

**Issue by Amit366** [Tech-N-Science/FunwithScience#493]
**Is your feature request related to a problem? Please describe.**
Add mathematical induction calculator to the algebra section. The definition shouldn't be plagiarized.

**Comment by ROUSHNI1** [comment]
Hello, I am a GSSOC'22 participant and I have knowledge about mathematical induction and i would like to contribute in this issue, can you Please assign it to me.

**Comment by Amit366** [comment]
@ROUSHNI1 u can work
