### ISSUE TITLE
Series and Parallel Calculator 

### ISSUE THREAD

**Issue by lakshrav** [Tech-N-Science/FunwithScience#494]
Feature: A series and parallel calculator under physics electromagnetism.
To find the equivalent resistance/capacitance value.

If this feature is okay, could you please assign me this task? 
I am contributing under GSSoC 22 by the way.

**Comment by Amit366** [comment]
@lakshrav while  creating the calculator the definition should not be copied from any website and also u need to add the solution steps for the calculator as done in other physics calculators like force, collision

**Comment by lakshrav** [comment]
Sure will keep these in mind.
Thanks!

**Comment by shahishree03** [comment]
Can you please assign me in this .I like to work

**Comment by lakshrav** [comment]
Hey, yes I'm working on it
