### ISSUE TITLE
Relativistic Mass section 

### ISSUE THREAD

**Issue by shivvamm** [Tech-N-Science/FunwithScience#497]
**Is your feature request related to a problem? Please describe.**
No it's not related to a problem .As in relativity we have relativistic velocity we also have relativistic mass 

**Describe the solution you'd like**
To add a new section of RELATIVISTIC MASS  and use the formula m =m0 / under root of (1-v^2/c^2)

**Describe alternatives you've considered**
The value of m0 and v are given we already know the value of c and find the ans 

**Additional context**
In addition there is one more to add in RELATIVITY this will be considered as a 2nd part of RELATIVISTIC MASS or a whole new section to find RELATIVISTIC Momentum the formula is same as moment multiply the ans of above mass obtained to velocity given this is just and extension

**Comment by shivvamm** [comment]
I want to add this feature and and work on this

**Comment by Amit366** [comment]
@shivvamm u can work but don't copy the definition from any website and also u need to add solution steps to the calculator as done in physics calculators.

**Comment by shahishree03** [comment]
Please I really eager to do contributions in this topic as GSSOC22

**Comment by Amit366** [comment]
@shivvamm r u working?

**Comment by shivvamm** [comment]
> @shivvamm r u working?

yes sir i already did it

**Comment by shivvamm** [comment]
Sir PLEASE accept the pull request
