### ISSUE TITLE
The card overlaps with Navbar when hovered

### ISSUE THREAD

**Issue by sebinfrancis7** [Tech-N-Science/FunwithScience#498]
**Describe the bug**
The Explore cards under Learn section overlaps with the Navbar on hover.

**To Reproduce**
1. Go to learn section
2. Hover on any of the three cards.
3. The cards overlap the Navbar

**Expected behavior**
The Navbar should not be under the card at any time.

**Screenshots**
![image](https://user-images.githubusercontent.com/59263190/156599137-0542ab89-948a-4057-9eb4-fc77e6ac8700.png)

I would like to work on fixing this bug as part of GSSoC 2022. Can you please assign this issue to me. Thank you.

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [e.g. chrome, firefox]

**Smartphone (please complete the following information):**

**Additional context**

I would like to work on fixing this bug as part of GSSoC 2022. Can you please assign this issue to me. Thank you.

**Comment by sebinfrancis7** [comment]
@Amit366 can you please assign this issue to me as part of GSSoC.

**Comment by Amit366** [comment]
@sebinfrancis7 the card doesn't overlap

**Comment by Amit366** [comment]
@sebinfrancis7 u can work
