### ISSUE TITLE
Add a button to plot a graph for the functions in the Geometric section

### ISSUE THREAD

**Issue by Khaled-Damaj** [Tech-N-Science/FunwithScience#499]
I want to add a feature ,where the user can generate a graph of the equation that he/she chooses,bu clicking on the button named "Plot Graph" to plot the equation.

**Comment by Khaled-Damaj** [comment]
I want to be assigned to this feature if it's possible.

**Comment by Amit366** [comment]
@Khaled-Damaj will u add the graph feature? Like on clicking the button the graph will be plotted?

**Comment by tasneemahmed123** [comment]
I want to add a feature ,where the user can generate a graph of the equation that he/she chooses,by clicking on the button named "Plot Graph" to plot the equation.

**Comment by Amit366** [comment]
@tasneemahmed123 will u even make a feature to plot graphs?

**Comment by sonalee21** [comment]
Hello,
I would like to work on this issue, please assign it to me.

**Comment by Amit366** [comment]
@sonalee21 its not just adding a button. with the button u need to add the functionality to represent graph

**Comment by sonalee21** [comment]
Okay @Amit366 , assign it to me. I'll do it.

**Comment by Samiksha-Garg** [comment]
Hi, I would like to work on this issue. I can use openSource libraries for plotting graph right?

**Comment by Amit366** [comment]
@Samiksha-Garg u can work. Yes u can use

**Comment by Samiksha-Garg** [comment]
@Amit366 Please Assign it to me :)
