### ISSUE TITLE
Matrices and Determinant Calculator

### ISSUE THREAD

**Issue by aku1310** [Tech-N-Science/FunwithScience#502]
### Matrices
Add information and create  matrix multiplication, inverse matrix, transpose of a matrix calculator.

### Determinants
Add information on determinants and create determinant calculator.

**Comment by aku1310** [comment]
Hello, I am a GSSOC'22 participant and I have knowledge about matrices and determinants and would like to contribute in this issue.

**Comment by Amit366** [comment]
@aku1310 the definition should be copied from other sites and also add the solution steps for the calculator as done in physics calculators like force.

**Comment by suman-shah** [comment]
Hello, I am a GSSOC'22 contributor i would like to contribute here please assign me this issue . I can add step by step procedure to solve matrix problem i.e. multiplication, inverse matrix, transpose addition  subtraction too

**Comment by riyajaiswal25** [comment]
I want to work on this issue

**Comment by Amit366** [comment]
@riyajaiswal25 u can work

**Comment by the-illuminatus** [comment]
is this issue still unresolved?

**Comment by the-illuminatus** [comment]
if yes, then i would like to work on it.

**Comment by Amit366** [comment]
@the-illuminatus u can work

**Comment by tushar-glitch** [comment]
I want to work on this issue. I can make a matrix and determinant calculator.

**Comment by Samiksha-Garg** [comment]
Hello, I am a SSOC'22 participant, and would like to work on this issue. Since matrices is a big topic, I can first start on the determinant calculator of square matrices.

**Comment by Amit366** [comment]
@Samiksha-Garg u can work
