### ISSUE TITLE
Enhancement : Adding customized look to standard scroll bar

### ISSUE THREAD

**Issue by TG922** [Tech-N-Science/FunwithScience#514]
### Description

- I want to add custom scroll bar for this website.
- This will Improve your website’s **User Interface(UI)**.
- Please assign me on this issue under GSSOC '22.

**Comment by TG922** [comment]
[ ] 👀 I have read the [**Contributing**] (https://github.com/Tech-N-Science/FunwithScience/blob/17d5fcebb3283fd42fe35f158d278dafd50bc575/CODE_OF_CONDUCT.md) document.
I would like to work on this issue, can you please assign me? I am a GSSOC'22 participant.
Kindly assign me this issue.

**Comment by Amit366** [comment]
@TG922 there is no need for the scroll bar for now
