### ISSUE TITLE
Bug in Connect with us section

### ISSUE THREAD

**Issue by Priyanshi136** [Tech-N-Science/FunwithScience#518]
**Describe the bug**
In the footer section of the home page, the connect with us links are not working properly like, the linkedin, and instagram and other links also. They are not going to their respective profile pages.

**To Reproduce**
1. Go to home page, footer section
2. Click on the icon of linkedin or instagram
3. See error

**Expected behavior**
After clicking on  the links, there must be opened the profile page of respective apps.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by Amit366** [comment]
That's because we haven't added the facebook and instagram links
