### ISSUE TITLE
The buttons are not aligned in center

### ISSUE THREAD

**Issue by shivvamm** [Tech-N-Science/FunwithScience#523]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Amandev02** [comment]
hi @shivvamm can u assign me this issue

**Comment by Amit366** [comment]
@shivvamm which buttons are not alligned?

**Comment by shivvamm** [comment]
![Screenshot_2022-03-06-15-39-12-618_com.android.chrome.jpg](https://user-images.githubusercontent.com/58168590/156918610-9d6db597-d75d-4f44-b7fc-ec8db810b529.jpg)

**Comment by shivvamm** [comment]
> @shivvamm which buttons are not alligned?

If would be good if they are aligned in centre all of them

**Comment by Amit366** [comment]
@shivvamm but in different mobile views its differently alligned

**Comment by shivvamm** [comment]
Yea it is left aligned which is bit odd

**Comment by Amit366** [comment]
ok work on it

**Comment by shivvamm** [comment]
Yes sir on it I will send the pr soon ☺️

**Comment by dvlsatya** [comment]
i would like to work on this issue . can you please assign me?

**Comment by Amit366** [comment]
@dvlsatya u can work

**Comment by Amit366** [comment]
@dvlsatya any update?

**Comment by tasneemahmed123** [comment]
Sir, can I work in this issue too ? I will try to align all these buttons on center and if I see any update while I am working I will tell you here or ping you on discord to tell me your opinion

**Comment by Amit366** [comment]
@tasneemahmed123 u can work

**Comment by rohitkhicher001** [comment]
I would like to work on this issue.

**Comment by Amit366** [comment]
Its not required as of now
