### ISSUE TITLE
Calculate Capicitance and Resistance 

### ISSUE THREAD

**Issue by shahishree03** [Tech-N-Science/FunwithScience#527]
It's often complex 🤔 and takes  time to understand how to solve Capicitance and Resistance in the circut network.😅

** About the website** 😀😀
_____________________________________________
Design a responsive website that one can calculate their "**Resistance**  " and "**Capicitance** " easily and can understand by steps .
🚩User just have to design circuits and put Resistance with their values .😄 After this it can calculate the network and executing the resistance or capacitor based on the inputs step by steps.
🚩User can also simply understand the concept  step by step by sample questions available on the websites. 👍

**Comment by shahishree03** [comment]
Hi 👋 I am Shahi Shreshth and GSSOC22 contributor.
Please assigned me this issue.
I have knowledge about the resistance and Capicitance ,and able to solve complex networks.

**Comment by Amit366** [comment]
@shahishree03 go ahead

**Comment by shahishree03** [comment]
Thank you
