### ISSUE TITLE
Text of about us and contact does not have the link of them respectively.

### ISSUE THREAD

**Issue by Chavda-Mitul** [Tech-N-Science/FunwithScience#532]
**Describe the bug**
In the home page at bottom the about text should also redirect have the link same as about us logo same issue with contact us right next to it.
**To Reproduce**
1. Go to 'about us '
2. Click on 'about us and contact us text'
3. It is not linked.

**Expected behavior**
hovering over the about us and contact us text the the cursor should change from a pointer to a small hand.

**Screenshots**
![image](https://user-images.githubusercontent.com/82195661/156909330-72e315eb-4660-40fd-8f22-f10c241f1cf7.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [99.0.4844.51]

**Comment by Chavda-Mitul** [comment]
I can work on this assign it to me.

**Comment by Amit366** [comment]
@Chavda-Mitul for now only work on contact us and mail

**Comment by purohitmansi** [comment]
Hello @Amit366!

I am a GSSoC22 contributor. I would love to work on this issue and make PR as soon as I resolve the issue. Please do assign this to me.

ThankYou:)

**Comment by Amit366** [comment]
@Chavda-Mitul r u working?

**Comment by Chavda-Mitul** [comment]
Yes I am working on it.

**Comment by itsAftabAlam** [comment]
I would like to work on this issue, please assign this to me

**Comment by Amit366** [comment]
@itsAftabAlam add only for contact and mail .

**Comment by itsAftabAlam** [comment]
sure @Amit366

**Comment by SainathPoojary** [comment]
Hi! @Amit366 , I would like to work on this Issue. Can you please assign it to me.

**Comment by Amit366** [comment]
@itsAftabAlam since there is no update so I am assigning it to @SainathPoojary

**Comment by Amit366** [comment]
@SainathPoojary go through the above chats and see what u have to do

**Comment by SainathPoojary** [comment]
@Amit366 Can you please confirm, If its working as expected.

https://user-images.githubusercontent.com/53347682/161376420-f0b301dd-2417-49cf-b436-67ead42966b0.mp4
