### ISSUE TITLE
I will update how to contact us section by changing cases and making it sound better.

### ISSUE THREAD

**Issue by AyushJain001** [Tech-N-Science/FunwithScience#538]
**Is your feature request related to a problem? Please describe.**
It seems that the contact section has not describe properly and there is a mistake in Alphabet cases . So I want to work on that.
**Describe the solution you'd like**
I will change the contact the section more readable form .
![Screenshot (449)](https://user-images.githubusercontent.com/90152799/156919238-85cde821-aa7b-4304-a99b-92656179f10a.png)
![Screenshot (449)](https://user-images.githubusercontent.com/90152799/156919260-68690734-d818-4750-b72b-36889667cdb2.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by AyushJain001** [comment]
Please assign it to me  under GSSOC22 .

**Comment by Amit366** [comment]
ok

**Comment by AyushJain001** [comment]
okay..I start working on the same

**Comment by AyushJain001** [comment]
Updated contact us description. @Amit366 please see and merge if sounds good.

**Comment by Amit366** [comment]
@AyushJain001 u should send the pull request to the main repo and not to ur own repo

**Comment by AyushJain001** [comment]
@Amit366 please look the changes made. If sounds good , you may merge the code. Thanks
