### ISSUE TITLE
Add Solution part in Poiseuille's law calculator in Fluid Mechanics section inside Classical Mechanics.

### ISSUE THREAD

**Issue by AnuragParashar2000** [Tech-N-Science/FunwithScience#540]
Add Solution part in Poiseuille's law calculator in Fluid Mechanics section inside Classical Mechanics, you can see other physics calculators for your reference.

**Comment by Harshitp7** [comment]
> Add Solution part in Poiseuille's law calculator in Fluid Mechanics section inside Classical Mechanics, you can see other physics calculators for your reference.

I want this issue to be assigned. I am a GSSoC'22 contributor.

**Comment by Sukriti-m** [comment]
Hey @Amit366 
I would like to work on this issue. I'd be grateful if you could assign this task to me under GSSOC'22.

**Comment by Sukriti-m** [comment]
Hey @Amit366 
I would like to work on this issue. I'd be grateful if you could assign this task to me under GSSOC'22.

**Comment by Amit366** [comment]
@Sukriti-m u can work
