### ISSUE TITLE
Add Solution part in Bernoulli's equation calculator in Fluid Mechanics section inside Classical Mechanics.

### ISSUE THREAD

**Issue by AnuragParashar2000** [Tech-N-Science/FunwithScience#541]
Add Solution part in Bernoulli's equation calculator in the Fluid Mechanics section inside Classical Mechanics, you can see other physics calculators for your reference.

**Comment by sinha-toyeesh** [comment]
I would like to work on this issue, please assign it to me , I'm a GSSOC contributor.

**Comment by Amit366** [comment]
ok
