### ISSUE TITLE
Improvisation of UX of footer

### ISSUE THREAD

**Issue by ronitrangwani** [Tech-N-Science/FunwithScience#545]
UX of the footer of the website is not up to mark.
I want to work on this under GSSOC2022 to make it more user-friendly. Can you assign it to me.

**Comment by Amit366** [comment]
@ronitrangwani what type of changes do u want to do?

**Comment by ronitrangwani** [comment]
UX of the footer section doesn't match with the other component of the site, and it's not properly align. So I would like to correct that.
