### ISSUE TITLE
"Scroll  Back to Top" arrow does not disappears when it is at the top

### ISSUE THREAD

**Issue by roushandas02** [Tech-N-Science/FunwithScience#546]
**Describe the bug**
"Scroll  Back to Top" arrow is present even when it is at the top. 

**Expected behavior**
The "Scroll  Back to Top" arrow should disappear as soon as it reaches the top.

**Screenshots**
![Screenshot (252)_LI](https://user-images.githubusercontent.com/100259231/157105044-71b29d83-6b0c-45ab-8793-1febd7abfd45.jpg)

**Additional context**

**Comment by meghamalviya5** [comment]
Hi @roushandas02, so this  "Scroll Back to Top" arrow should appear only when we reach the bottom of the page or it should be omitted only from the topmost screen?

**Comment by roushandas02** [comment]
Yes, it should be omitted only from topmost screen

**Comment by meghamalviya5** [comment]
Okay. Please assign this issue to me. I am a GSSoC contributor.

**Comment by Amit366** [comment]
@roushandas02 r u working on this issue?

**Comment by roushandas02** [comment]
Yes @Amit366 , I would like to work on this issue

**Comment by Amit366** [comment]
ok go ahead

**Comment by Prikshit-anthal** [comment]
Kindly assign me this issue,it wont take much time. I'm a participant in GSSOC.

**Comment by Amit366** [comment]
@Prikshit-anthal u can work
