### ISSUE TITLE
Issue in About page

### ISSUE THREAD

**Issue by vaibhavchaubey** [Tech-N-Science/FunwithScience#549]
**Describe the bug**
About page is not working.

I am interested in working on this issue as a GSSoC'22 participant.
@Amit366  Please assign it to me.

**Comment by Amit366** [comment]
@vaibhavchaubey r u interested?

**Comment by BIKRAM-SAHA** [comment]
Hi, @Amit366  as it has been 21 days since this issue was opened yet no-one has been assigned to solve it, I would like to be assigned. I am interested in implementing the about page.

**Comment by Amit366** [comment]
@vaibhavchaubey u need to add About us in the home page itself just above the learn heading. And also don't copy the contents from any other website.
