### ISSUE TITLE
Springs Combination Calculator in Classical mechanics

### ISSUE THREAD

**Issue by VATSAL-IIT** [Tech-N-Science/FunwithScience#550]
A calculator for equivalent spring constant for a cobination of springs

**Comment by VATSAL-IIT** [comment]
I want to work on this issue under JWOC

**Comment by Amit366** [comment]
@VATSAL-IIT since u failed to send the Pull request so I am removing the label but anyways u can work if u want

**Comment by VATSAL-IIT** [comment]
Sure!

**Comment by Sukriti-m** [comment]
Hey @Amit366 @AnuragParashar2000
I would like to work on this issue. I'd be grateful if you could assign this task to me under GSSOC'22.

**Comment by Sukriti-m** [comment]
Hey @Amit366 @AnuragParashar2000
I would like to work on this issue. I'd be grateful if you could assign this task to me under GSSOC'22.

**Comment by Amit366** [comment]
@Sukriti-m u can work
