### ISSUE TITLE
Update GSSoC'22 in README.md

### ISSUE THREAD

**Issue by SainathPoojary** [Tech-N-Science/FunwithScience#552]
Hi @Amit366 👋,
I am a contributor at GSSoC'22.
I saw "Open Source Programs we have been associated with" section was missing GSSOC'22
I want to work on that,
Please assign it to me.
 
### Current "Open Source Programs we have been associated with" section
![image](https://user-images.githubusercontent.com/53347682/157273273-455b2aa5-2e17-463d-97cb-2326e55831b6.png)

**Comment by Amit366** [comment]
@SainathPoojary u can work

**Comment by SainathPoojary** [comment]
Yes @Amit366, I am Interested.

**Comment by Amit366** [comment]
U can work

**Comment by SainathPoojary** [comment]
Hi @Amit366, I have raised a Pull Request for this issue. Please review it.
