### ISSUE TITLE
Wrong Information in Torque Calculator

### ISSUE THREAD

**Issue by BabyElias** [Tech-N-Science/FunwithScience#554]
![tempsnip](https://user-images.githubusercontent.com/95405559/157374911-57ec5473-fed0-4994-8c27-89b97c371406.png)
In the inertia tab , description has enter *force applied in Newtons*(kg-m/s2) but Inertia is the Moment of inertia of the body that is measured in kg-m2. 

There can be two ways to resolve this issue :
1) Add a *choose the object* form label, where we will have some standard objects/shapes(like disc,ring,cylinder,sphere,etc) whose 
   MOI will be automatically fetched by the website without having the user to enter it. And in case its not some standard shape but 
   the user knows the MOI, add a custom MOI tab for the user to enter.

2) Simply,just change the description of Inertia form label.

I am a GSSoC Contributor.Please assign me this issue and inform me about which option to consider.

**Comment by Amit366** [comment]
@BabyElias just change the label as the MOI is calculated in other calculator

**Comment by BabyElias** [comment]
Ok. Will do it.

**Comment by AnuragParashar2000** [comment]
The Labels are fine now but please change the sign of torque(Tau), now the sign is: 
![image](https://user-images.githubusercontent.com/73629391/158005408-d52cbf31-9e30-4928-96cc-c1e828516807.png)
Earlier it was: 
![image](https://user-images.githubusercontent.com/73629391/158005393-68d50a98-9bfa-4f9c-92bc-06c7c976df04.png)
