### ISSUE TITLE
Wrong Information in Work Calculator

### ISSUE THREAD

**Issue by BabyElias** [Tech-N-Science/FunwithScience#555]
![tempsnip](https://user-images.githubusercontent.com/95405559/157375955-52b45b86-57ec-436f-a1be-6b2ededf4196.png)

The label says Torque(in N-m) and description asks the user to enter Force applied(in N).
The name of this label should be actually changed to *force* and a separate label asking the user to enter the *distance from the axis of rotation where force is applied* should be added to ensure the correctness of the formula.

I am a GSSoC contributor.Kindly assign me this issue.

**Comment by Amit366** [comment]
@BabyElias u can change the label

**Comment by BabyElias** [comment]
So,should I also add the other label of enter distance from axis of rotation one?

**Comment by AnuragParashar2000** [comment]
@Amit366  I have reviewed this PR and the labels are resolved now.
