### ISSUE TITLE
Show/Hide Password functionality

### ISSUE THREAD

**Issue by Siddhesh777** [Tech-N-Science/FunwithScience#557]
**Is your feature request related to a problem? Please describe.**
Sometimes user needs to view the password he/she entered.
There is no option to view the password while typing it.

**Describe the solution you'd like**
I will create a button which will toggle its view(show/hidden) using react hook useState

**Additional context**
I am contributor at gssoc'22.
Please assign this to me.

**Comment by alamsameer** [comment]
Can i work on it

**Comment by Amit366** [comment]
@Siddhesh777 u can work

**Comment by tasneemahmed123** [comment]
HI, can i work on this issue?
