### ISSUE TITLE
Improve the cover page 

### ISSUE THREAD

**Issue by kheya19** [Tech-N-Science/FunwithScience#562]
I can improve your cover page with some illustrations and a little bit of animation.

**Comment by Amit366** [comment]
@kheya19 can u exactly suggest the changes?

**Comment by kheya19** [comment]
> @kheya19 can u exactly suggest the changes which u want to do?

I will replace your cover page image with illustration related to your website and also I want to add some shapes which will be animated

**Comment by tasneemahmed123** [comment]
Hi , can i work on this issue , I will try to improve cover page by adding some featured and amazing animations

**Comment by Amit366** [comment]
@tasneemahmed123 can u tell what do u want to add?

**Comment by soumali28** [comment]
I want to work on this issue under GSSoC.
I will make the entire UI of the front page make the cards beautiful and animations and also make it entirely responsive.

**Comment by AnIkeT126** [comment]
can I work on this issue under GSSoC'22 @Amit366 ??

**Comment by tasneemahmed123** [comment]
> @tasneemahmed123 can u tell what do u want to add?

I will add some words and some animations , if it will seem cool

**Comment by Amit366** [comment]
@tasneemahmed123 u can work

**Comment by Kanika2772002** [comment]
hey , can i do it some changes if u @Amit366 assign me

**Comment by Amit366** [comment]
There's no such improvement required

**Comment by Kanika2772002** [comment]
Ok fine
