### ISSUE TITLE
Add Solution to Exponents Calculator in Algebra inside Math calculators.

### ISSUE THREAD

**Issue by AnuragParashar2000** [Tech-N-Science/FunwithScience#564]
Add Solution to Exponents Calculator in Algebra inside Math calculators. You can look at other math calculators for your reference.

**Comment by Harshitp7** [comment]
> Add Solution to Exponents Calculator in Algebra inside Math calculators. You can look at other math calculators for your reference.

I want this issue to he assigned. I am a contributor in GSSoC'22.

**Comment by Amit366** [comment]
@Harshitp7 r u interested?

**Comment by maura-dev** [comment]
Please assign this issue to me for gssoc.

**Comment by Amit366** [comment]
@maura-dev u can work
