### ISSUE TITLE
It seems that the website does not contain the scroll bar to the right. I would like to work on it and add to it.

### ISSUE THREAD

**Issue by AyushJain001** [Tech-N-Science/FunwithScience#568]
**Is your feature request related to a problem? Please describe.**
website does not contain the scroll bar for the movement.

**Describe the solution you'd like**
Scroll bar should be added.

**Describe alternatives you've considered**

**Additional context**

**Comment by AyushJain001** [comment]
Kindly assign me this issue under GSSOC. I would like to work on it.

**Comment by roy-shivam** [comment]
please assign me this issue under GSSOC 2022. i want to work on it.

**Comment by AyushJain001** [comment]
> Kindly assign me this issue under GSSOC. I would like to work on it.

Please assign this issue under GSSOC22

**Comment by Amit366** [comment]
There is no need for the scroll bar as of current state of website
