### ISSUE TITLE
formulae cheatsheet for maths , physics and physical chemistry along with named reaction in organic chemistry

### ISSUE THREAD

**Issue by Rahul101201** [Tech-N-Science/FunwithScience#571]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Rahul101201** [comment]
i would like to work on this issue

**Comment by Amit366** [comment]
@Rahul101201 we don't require a cheatsheet. But if u want u can work on chemistry part.
