### ISSUE TITLE
Adding option for Radians to trigonometric calculator

### ISSUE THREAD

**Issue by saujanyasood** [Tech-N-Science/FunwithScience#572]
**Is your feature request related to a problem? Please describe.**
There is no option to enter the angle value in radians to calculate trigonometric functions.

**Describe the solution you'd like**
I'd like to add the feature to enter the angle in radians as well as degrees, along with providing the option to enter it in terms of pi, which is a popular measurement of angles in radians.

<img width="771" alt="image" src="https://user-images.githubusercontent.com/76472083/158435477-5a5af62d-0664-4a01-9a51-b4d0d6eb1ab1.png">

**Additional context**
I am a Contributor at GirlScript Summer of Code 2022. (GSSOC)
I want to work on this issue. Please assign this issue to me.

**Comment by saujanyasood** [comment]
@Amit366 Can I work on this issue?

**Comment by Amit366** [comment]
@saujanyasood u can work

**Comment by riyajaiswal25** [comment]
I want to work on this issue

**Comment by Amit366** [comment]
@riyajaiswal25 u can work

**Comment by its-ayush-07** [comment]
Hello, can I work on this issue under SSOC?

**Comment by Amit366** [comment]
@its-ayush-07 ok
