### ISSUE TITLE
Adding Home button after quiz ends

### ISSUE THREAD

**Issue by aaryahjolia** [Tech-N-Science/FunwithScience#574]
**Is your feature request related to a problem? Please describe.**
When any quiz ends, user don't get any navigation ideas, so I want to add a home button when any quiz ends to go back to home.

![gssoc](https://user-images.githubusercontent.com/82600388/158950274-b8e97978-a1ad-404e-b5ab-7d06c6590736.png)

**Describe the solution you'd like**
 A home button will appear below the marks obtained by user.
Something like this : 
(Colour and font will be adjusted. This is just a sample.)

![gssoc](https://user-images.githubusercontent.com/82600388/158950494-18f170dc-920a-4880-8f4f-a9c262d48da3.png)

I want to work on this issue under GSSoC'22.

**Comment by Megh2507** [comment]
Hey! I have already implemented that home button below the quiz score. After the quiz ends and after clicking that button it will directly render the user to Home page . It looks like the following.
**Before Clicking:**
![Fun with Science - Tech N Science - Google Chrome 19-03-2022 03_53_56](https://user-images.githubusercontent.com/73662865/159092966-194d995e-53ab-44ba-8ae4-8ee67e151ad0.png)
**After Clicking:**
![Fun With Science - Tech N Science - Google Chrome 19-03-2022 04_07_48](https://user-images.githubusercontent.com/73662865/159093630-7a4a5fb6-51b4-44a0-b833-500bc7154c87.png)
I want to work on this.

**Comment by Amit366** [comment]
@aaryahjolia its a good feature but the design is not good.

**Comment by aaryahjolia** [comment]
Yes @Amit366 , the design is only for visual representation since I created that in paint, I will make that a good one and will implement changes as per requirement!

**Comment by Amit366** [comment]
@aaryahjolia u can work

**Comment by SHRUTI-SINGH16** [comment]
I would like to work on this issue. Please assign me as a GSSOC 2022 Contributor.

**Comment by tushar-glitch** [comment]
Can I work on this issue? I will add a home button after the quiz ends

**Comment by Amit366** [comment]
@tushar-glitch u can work on this

**Comment by akanksha0812** [comment]
Please assign this issue to me

**Comment by Amit366** [comment]
@akanksha0812 u can work

**Comment by its-ayush-07** [comment]
Can I work on this under SSOC?

**Comment by Amit366** [comment]
@its-ayush-07 u can work
