### ISSUE TITLE
Add a play again option after every quiz

### ISSUE THREAD

**Issue by Megh2507** [Tech-N-Science/FunwithScience#575]
**I want to add a play again option after every quiz ends like the following.**
![Fun with Science - Tech N Science - Google Chrome 19-03-2022 11_01_59](https://user-images.githubusercontent.com/73662865/159108608-22d1d33f-8709-4e0f-b6b1-e6a0327de4e5.png)

I want to work on this issue under GSSOC'22.

**Comment by Amit366** [comment]
@Megh2507 u can work

**Comment by Amit366** [comment]
@Megh2507 r u working?

**Comment by Kanika2772002** [comment]
Hi , it seems i can add it @Megh2507 , so can u assign me

**Comment by Amit366** [comment]
@Kanika2772002 u can work

**Comment by vedsom** [comment]
Is this issue has been resolved @Amit366 ?
otherwise i can add it.

**Comment by Amit366** [comment]
@vedsom u can work

**Comment by yvrjprshr** [comment]
I want to work on that issue, i am part of the HSOC program.

**Comment by Kanika2772002** [comment]
No, it doesn't. Bcz it have a lot of issues
