### ISSUE TITLE
Add new relevant svg images for physics and chemistry card

### ISSUE THREAD

**Issue by Megh2507** [Tech-N-Science/FunwithScience#576]
Three of the cards are having same svg images which is not looking relevant , I can change the svg images for physics and chemistry according to the the topic.
**I am talking about this section👇.**
![Fun with Science - Tech N Science - Google Chrome 19-03-2022 11_15_59](https://user-images.githubusercontent.com/73662865/159109095-0c8a5e0e-5848-4dae-9e38-0baf49a97ad3.png)
I want to work on this under GSSOC'22.

**Comment by Amit366** [comment]
@Megh2507 u can work
