### ISSUE TITLE
Confirm Password field while signing up.

### ISSUE THREAD

**Issue by Siddhesh777** [Tech-N-Science/FunwithScience#579]
**Is your feature request related to a problem? Please describe.**
Many times it may happen that the user entered the password and accidentally typed a wrong key.
Then user need to reset the password.

**Describe the solution you'd like**
We can create a confirm password field while signing up and if both the password match, then only we will register a new user.

![1](https://user-images.githubusercontent.com/77476772/159225500-03afeb61-6dc2-43a1-9367-a488a9247dbf.png)

**Additional context**
I am a contributor at gssoc'22.
Please assign this issue to me.

**Comment by Diksha4111** [comment]
Can I get the opportunity to work on this issue?

**Comment by Siddhesh777** [comment]
hey @Amit366 
Can you assign this task to me?😅

**Comment by Amit366** [comment]
@Siddhesh777 u can work
