### ISSUE TITLE
Only showing "contact" instead of "contact us"

### ISSUE THREAD

**Issue by AyushJain001** [Tech-N-Science/FunwithScience#581]
**Is your feature request related to a problem? Please describe.**
In the footer it is only showing "contact" instead of "contact us" title

**Describe the solution you'd like**
![Screenshot (451)](https://user-images.githubusercontent.com/90152799/159657579-f3b5ecf8-e3a7-4523-8295-1ba8d9146b36.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by AyushJain001** [comment]
Kindly assign this issue under GSSOC22

**Comment by Amit366** [comment]
@AyushJain001 I would suggest u to do some really good contributions and not just adding one word or correcting spellings. I hope u would find a really good bug to solve
