### ISSUE TITLE
Remove Warnings on compiling while setting up in local system

### ISSUE THREAD

**Issue by BIKRAM-SAHA** [Tech-N-Science/FunwithScience#596]
**Describe the bug**
while setting up the project at my local system I realized that it compiles with warnings. I propose to
1. remove the escape characters '\\.' and replace them with '.' 
2. delete line2 of funwithphysics\src\Components\LearnMore\index.js since it is imported but never used
3. replace '!=' with '!==' at line 3120 of funwithphysics\src\Components\Algebra\Topic\Calculator.js
4.  delete C3 from line 933 and line 934 of funwithphysics\src\Components\Geometry\Topic\Calculator.js as the variable C3 is assigned but never used in the calculation given below
5. replace the 'for' with 'htmlFor'
6. and replace 'class' with 'className'

**To Reproduce**
1. run `npm start` to start the development server at localhost:3000
2. see warnings at terminal
3. see error at console while at `localhost:3000`

**Expected behavior**
The code is supposed to compile without warning or errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/74536497/161287913-c3b2a905-1058-4814-ad20-3db1742971d8.png)
<img width="333" alt="2" src="https://user-images.githubusercontent.com/74536497/161288240-d257a9e6-17ce-4e6f-a297-ecf064b852ee.png">
<img width="327" alt="3" src="https://user-images.githubusercontent.com/74536497/161288454-ae4cdaf5-5fe7-40a4-8424-19e63d57de4d.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave

**Comment by BIKRAM-SAHA** [comment]
Please assign me the issue, so that I can start working on it

**Comment by Amit366** [comment]
u can work @BIKRAM-SAHA
