### ISSUE TITLE
Add Logarithm as a topic under algebra

### ISSUE THREAD

**Issue by maura-dev** [Tech-N-Science/FunwithScience#602]
Add a page in algebra that gives short note on logarithm with examples and logarithmic laws

**Comment by Amit366** [comment]
@maura-dev u can work

**Comment by Amit366** [comment]
#562  is already similar to this issue

**Comment by Architsharma7** [comment]
Can I work on this issue?

**Comment by Amit366** [comment]
@Architsharma7 u can work

**Comment by Architsharma7** [comment]
okay

**Comment by Architsharma7** [comment]
I've solved the issue, you can review it.
