### ISSUE TITLE
Bug in math quiz section

### ISSUE THREAD

**Issue by Amit366** [Tech-N-Science/FunwithScience#604]
**Describe the bug**
On clicking the quiz in math section the cursor doesn't click anything and when move back to previous page then nothing could be clicked.

**Comment by BIKRAM-SAHA** [comment]
## Does this issue corresponds to this bug?
On visiting maths quiz section for first time:
![image](https://user-images.githubusercontent.com/74536497/161843409-234d39e5-5376-4c6e-9016-51532025fff6.png)
On reloading:
![image](https://user-images.githubusercontent.com/74536497/161843472-7d4535b7-73e3-4891-bf31-a526974050b0.png)

**Comment by Amit366** [comment]
@BIKRAM-SAHA this issue is basically that when quiz page or math calculators page is opened then none of the buttons are clickable. Only after reloading they work
