### ISSUE TITLE
Add Steps to Permutation And Combination Calculator in Algebra section.

### ISSUE THREAD

**Issue by Sukriti-m** [Tech-N-Science/FunwithScience#606]
**Is your feature request related to a problem? Please describe.**
Add steps for Permutation And Combination Calculator in Algebra section, means on clicking calculator entire steps should appear. 

**Describe the solution you'd like**
I will add stepwise solution of the problems.

**Additional context**
I am contributor at GSSoC '22. Please assign this issue to me.

**Comment by Amit366** [comment]
@Sukriti-m this issue is already resolved
