### ISSUE TITLE
[bug] in readme.md file 

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Tech-N-Science/FunwithScience#607]
Hey , Greeting's of the day  :smile: 
As u know that readme.md  file is one the great doc's that reflect's or attract the organisation toward's ur repo 
I go through all the readme file and i found most of the grammitical and spacing error . 
So i request u  to assign this issue to me  . 
Thank u :blush:

**Comment by Amit366** [comment]
@Vikash-8090-Yadav can u point out any such error?

**Comment by Vikash-8090-Yadav** [comment]
```
Create a folder at your desire location (usually at your desktop).

in this there should  be desired in the place of **desire** ...
```
```
The use of sexualized language or imagery, and sexual attention or advances of any 

In the places of **sexualized** there should be sexualized
```
```
 confidentiality with regard to the reporter
There should be **about** in the place of with regard to ...
```
I am using the online grammar zeker zoho 
[Grammar checker](https://writer.zoho.com/writer/open/ehcj480b49bc922f24234822d61ece37330be?from=free_grammar_checker)


![Screenshot from 2022-04-11 04-15-07](https://user-images.githubusercontent.com/85225156/162643273-93e634b9-ff4d-4b09-9f2b-bbcfed85b562.png)
