### ISSUE TITLE
Bug in statistics calculator

### ISSUE THREAD

**Issue by Amit366** [Tech-N-Science/FunwithScience#614]
**Describe the bug**
The sorted data and mode fields provide wrong answers.

**Comment by PeritusDeveloper** [comment]
I want to work on this issue.

**Comment by Amit366** [comment]
@PeritusDeveloper u can work

**Comment by PeritusDeveloper** [comment]
how do I install the node modules?
npm install is not working...

**Comment by Amit366** [comment]
@PeritusDeveloper have u tried npm install inside the funwithscience folder?

**Comment by nik132-eng** [comment]
I See this issue is open and if still, this remains to complete. I want to work on this issue can you please assign it to me.

**Comment by Amit366** [comment]
@nik132-eng u can work

**Comment by nik132-eng** [comment]
resolve this issue please check it. @Amit366
