### ISSUE TITLE
Add steps to Thermal Expansion Calculator

### ISSUE THREAD

**Issue by Sukriti-m** [Tech-N-Science/FunwithScience#618]
**Is your feature request related to a problem? Please describe.**
I saw that the steps of Thermal Expansion Calculator in the Thermodynamics section are missing.

**Describe the solution you'd like**
I will add steps to Thermal Expansion Calculator

**Additional context**
![td](https://user-images.githubusercontent.com/93239528/163581373-1ccbe717-b0c1-4d56-a2e8-b394d8ce9319.png)

I would like to work on this issue. I'd be grateful if you could assign this task to me under GSSoC22.

@Amit366  @AnuragParashar2000

**Comment by Amit366** [comment]
@Sukriti-m u can work
