### ISSUE TITLE
Add: Mutual Inductance Calculator and Critical Angle (TIR) Calculator

### ISSUE THREAD

**Issue by k99sharma** [Tech-N-Science/FunwithScience#619]
**Is your feature request related to a problem? Please describe.**
I want to add Mutual Inductance Calculator in Electromagnetism and a Critical Angle Calculator in Photonics

**Comment by Amit366** [comment]
@k99sharma u can work but u need to make the solution part as well

**Comment by k99sharma** [comment]
Okay! I will try to do it and make PR as soon as possible.

**Comment by Sukriti-m** [comment]
@Amit366 If this task is being delayed, then please assign me this issue.
I am a GSSoC'22 contributor.

**Comment by Amit366** [comment]
@Sukriti-m its already added. If u want u can work either on chemistry part or on adding physics solutions.
