### ISSUE TITLE
Add Different more formulas to the Gravitation section

### ISSUE THREAD

**Issue by Amit366** [Tech-N-Science/FunwithScience#62]
**Is your feature request related to a problem? Please describe.**
Add contents inside gravitation folder.

**Describe the solution you'd like**
As there are many formulas in gravitation so need to add all . To do that add different contents in the gravitation section like acceleration, potential and so on and when user clicks on the topic then the calculator should appear.

**Comment by yash10019coder** [comment]
Hi I would like to work on this issue please assign it to me , we can add formulae for gravitation potential , gravitational potential energy , Effect of gravity on height and depth , gravitational field , and more others

**Comment by Amit366** [comment]
@yash10019coder go ahead.

**Comment by kushagra487** [comment]
Hi, I would like to work on this issue. Could you assign it to me?

**Comment by kushagra487** [comment]
Hi, I would like to work on this issue. Could you assign it to me?

**Comment by Amit366** [comment]
@kushagra487 r u a participant of WOC?

**Comment by kushagra487** [comment]
@Amit366 I am planning to be a participant of WOC but currently I'm not a participant of WOC.

**Comment by Amit366** [comment]
@kushagra487 if u r not a participant then u can contribute but if u want to take part then u need to fill the google form in the WOC website and send the proposal

**Comment by Amit366** [comment]
@kushagra487 now if u want to contribute then u can go ahead but it will not be counted for WOC

**Comment by kushagra487** [comment]
For WOC on one of the proposal format there was mentioned that it will give you a upper hand if you are already contributing in a particular project. So, I thought of contributing first on that basis.

**Comment by Amit366** [comment]
@kushagra487 Yeah that's true and this is the way but I want to make it clear that ur WOC contributions will count after the coding period starts. For now I can contribute for selection. Coz in one of the open source event a participant argued that he has contributed but not counted as he had contributed before the coding period.

**Comment by Amit366** [comment]
For now if u wanna take this issue then u need to add gravitational field, potential

**Comment by kushagra487** [comment]
Ok, I'll add them assign it to me

**Comment by Amit366** [comment]
Cool👍
