### ISSUE TITLE
Add a Scroll Bar in the Webpage

### ISSUE THREAD

**Issue by Shatakshi-Choudhary** [Tech-N-Science/FunwithScience#621]
Scroll Bar in HTML is one of the features to scroll data from both horizontal and vertical formats. We will allocate the border, height, and width of the scroll tables. 
Suppose we want to add a scroll bar option in HTML, we will use an “overflow” option, and set it as auto-enabled for adding both horizontal and vertical scroll bars. And if we want to create a scroll bar either horizontal or vertical, then we will use "overflow-x" or "overflow-y".
Example- 
         {
             Overflow-x : scroll  ;       //add horizontal bar option in html
             Overflow-y : scroll ;       //add vertical bar option in html
          }
Hey! @Amit366 , I want to add this feature of Scroll Bar in FunwithScience website so that it can look more attractive & users can identify that there is more content in the webpage.

**Comment by Shatakshi-Choudhary** [comment]
Hey @Amit366 , Please assign this issue to me. I will add this feature of the Scroll Bar to the website by using HTML. I am a GSSoC'22 contributor & will try my best to add this feature.

**Comment by Amit366** [comment]
@Shatakshi-Choudhary there is no need for a scroll bar as of now. So I would suggest you to check out other opened issues.

**Comment by Shatakshi-Choudhary** [comment]
Okay!
