### ISSUE TITLE
Add Malus Law Calculator in Photonics calculators inside Physics Section.

### ISSUE THREAD

**Issue by AnuragParashar2000** [Tech-N-Science/FunwithScience#623]
Add malus law Calculator in Photonics calculators inside physics Calculator. You can look at other physics calculators for your reference.

**Comment by singhnaveen098** [comment]
Please assign it to me, i am a GSSOC contributor

**Comment by Amit366** [comment]
@singhnaveen098 u can work but remember to add the solution part as well.
