### ISSUE TITLE
Add Imaginary roots in quadratic eq calc

### ISSUE THREAD

**Issue by Sukriti-m** [Tech-N-Science/FunwithScience#628]
**Is your feature request related to a problem? Please describe.**
I saw that when the roots are imaginary in quadratic equation calculator then it just displays the message and does not show the value of complex roots.

**Describe the solution you'd like**
I will add the feature in which if the roots are imaginary then values of complex roots in the form of a+ib and a-ib will be shown
**Additional context**
![quad](https://user-images.githubusercontent.com/93239528/164374704-ff357263-984d-4443-b733-f740bd5642cd.png)

I would like to work on this issue. I'd be grateful if you could assign this task to me under GSSoC22.

@Amit366 @AnuragParashar2000

**Comment by Amit366** [comment]
@Sukriti-m u can work
