### ISSUE TITLE
Redirecting directly to home page after logging in

### ISSUE THREAD

**Issue by ajeetdangi2** [Tech-N-Science/FunwithScience#632]
**Is your feature request related to a problem? Please describe.**
An alert is shown when the user has successfully logged in.

**Describe the solution you'd like**
Instead of showing an alert we can directly redirect the user to the home page for a better User experience as it's better to have minimum clicks.

@Amit366 @AnuragParashar2000 Please assign this issue to me under GSSoC'22

**Comment by Amit366** [comment]
@ajeetdangi2 ok but if the login credentials are wrong then pop up should appear
