### ISSUE TITLE
Footer linkedIn link not working fine

### ISSUE THREAD

**Issue by ajeetdangi2** [Tech-N-Science/FunwithScience#635]
**Describe the bug**
When we click on the linkedIn icon in the footer it redirects to the link like "http://localhost:3000/https://www.linkedin.com/company/tech-n-science" instead of "https://www.linkedin.com/company/tech-n-science"
<img width="575" alt="Screenshot (5)" src="https://user-images.githubusercontent.com/72207545/165624459-424c1bf5-6600-49e3-9b53-564effa0f4d5.png">

@Amit366 Please assign me this issue under GSSoC'22

**Comment by tasneemahmed123** [comment]
Can you assign me this issue @ajeetdangi2

**Comment by Amit366** [comment]
@ajeetdangi2 u can work.
