### ISSUE TITLE
Degree Of Freedom Calculator in Thermodynamics section

### ISSUE THREAD

**Issue by Sukriti-m** [Tech-N-Science/FunwithScience#639]
**Describe the solution you'd like**
Add a Degree Of Freedom Calculator in Thermodynamics section for monoatomic, diatomic and triatomic gases.

**Additional context**
I am a GSSoC'22 contributor.
Please assign this issue to me.
@Amit366 @AnuragParashar2000

**Comment by Amit366** [comment]
@Sukriti-m these calculators are not required as of now. If u want then u can write solutions to the questions in physics section. If you want to know more on how to go about it then dm on discord
