### ISSUE TITLE
ADD solutions to the questions

### ISSUE THREAD

**Issue by Amit366** [Tech-N-Science/FunwithScience#640]
**Is your feature request related to a problem? Please describe.**
Add solutions to the physics questions (MCQs and numericals).

**Comment by piyusha2001** [comment]
Hello can I work on this under GSSOC'22?

**Comment by Amit366** [comment]
@piyusha2001 u can work. For any doubts u can ask in discord.

**Comment by SHRUTI-SINGH16** [comment]
I would like to work on this issue. Please assign me as a GSSOC 2022 Contributor.

**Comment by Amit366** [comment]
@SHRUTI-SINGH16 u can work. Just add proper step wise solution to math or physics questions in the editorial section.

**Comment by akanksha0812** [comment]
please assign this issue to me

**Comment by Sampurankishoresrivastava** [comment]
Please assign this to me.

**Comment by Amit366** [comment]
@Sampurankishoresrivastava @akanksha0812 u can work on adding solutions to both math and physics questions

**Comment by jatin00000** [comment]
Please assign me this issue. I would like to add editorial for Physics Question.

**Comment by Amit366** [comment]
@jatin00000 r u a part of any open source event?

**Comment by jatin00000** [comment]
Yes, Want to contribute under Hacktoberfest.

**Comment by Amit366** [comment]
@jatin00000 u can work. U need to add the solutions to the physics questions and not physics quiz.

**Comment by jatin00000** [comment]
Facing this issue in running 
npm start
![Untitled1](https://user-images.githubusercontent.com/94428262/195977050-e20e4951-243e-42db-a00a-451f6cf137ad.jpg)
![Untitled](https://user-images.githubusercontent.com/94428262/195977057-1352b157-22ad-4cec-87b0-de3f261cd09d.jpg)

**Comment by jatin00000** [comment]
I had gone through the code, and understood where to add the required code but not able to execute the code in my local machine.

**Comment by jatin00000** [comment]
![image](https://user-images.githubusercontent.com/94428262/195977196-32f4df6b-6c8d-403e-a400-dba8948e3dfa.png)

**Comment by Amit366** [comment]
@jatin00000 have u gone through the procedure in the readme file

**Comment by Amit366** [comment]
There is a section in the readme file of how to start. Go through it
