### ISSUE TITLE
Bug Report: The links in the footer page is not working.

### ISSUE THREAD

**Issue by MonalikaPatnaik** [Tech-N-Science/FunwithScience#643]
The links mentioned in the footer page is not working, I would like to work on it under GSSoC'22.
![bug](https://user-images.githubusercontent.com/99353300/167356870-14a5d59c-e255-4eb2-a3b3-394fb13b7122.PNG)

**Comment by Abhilasha-Jairath** [comment]
I want to work on this under GSsoc 2022 , Can you please assign it to me .

**Comment by Amit366** [comment]
@MonalikaPatnaik as we haven't add the accounts so its not working
