### ISSUE TITLE
Edit Style of sidebar in questions page.

### ISSUE THREAD

**Issue by AhmedKhaled590** [Tech-N-Science/FunwithScience#645]
**Describe the bug**
Under GSSoC22
Sidebar labels and buttons need to have a little margin to look more beautiful.

**Screenshots**
![image](https://user-images.githubusercontent.com/62337087/168394653-a0b68de0-5792-40ea-981f-44d54cd6c621.png)

**Comment by Amit366** [comment]
@AhmedKhaled590 u can work
