### ISSUE TITLE
Improve UI of contact form

### ISSUE THREAD

**Issue by Adhetya** [Tech-N-Science/FunwithScience#647]
**Describe the bug**
UI of contact form is not looking very good

**To Reproduce**
1. Go to website
2. Click on contact 
4. See form

**Expected behavior**
UI can be made better with font change and different color for button

**Screenshots**
<img width="1438" alt="Screenshot 2022-05-15 at 12 02 58 PM" src="https://user-images.githubusercontent.com/20537150/168460432-9832af71-f882-45de-9147-464ce0c11659.png">

I am GSSOC 22 contributor. Please assign this issue to me.

**Comment by Amit366** [comment]
@Adhetya what font changes and color change would u do. Like there is only a single button and font is also appropriate.

**Comment by Adhetya** [comment]
@Amit366, change button color, font does not match with rest of the website, reduce border-radius of website, change background color.

**Comment by Amit366** [comment]
@Adhetya u can work but it must look better than the current one.
