### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by sudeep162002** [Tech-N-Science/FunwithScience#651]
**Is your feature request related to a problem? Please describe.**
this project have large codebases and its going to become big in future as well so to manage such a big code base we need unit test for react  this will save time for many contributors and also it helps admin to check weather any new pr has merge conflict with other or not.

**Describe the solution you'd like**
I write unit test cases for different codes in repo

**Comment by Amit366** [comment]
@sudeep162002 u can work

**Comment by sudeep162002** [comment]
ok thanks
