### ISSUE TITLE
Enhance Algebra,Trigonometry,Geometry, and Integration topics Cards 

### ISSUE THREAD

**Issue by HazemAbdo** [Tech-N-Science/FunwithScience#652]
**Describe the bug**
Under GSSoC22
Change colors and the design of cards in the Algebra, Trigonometry, Geometry, and Integration pages.

**Screenshots**
![image](https://user-images.githubusercontent.com/59124058/169589023-b96f9f00-efe7-4513-aeb5-520f1cad9d5d.png)

**Comment by Amit366** [comment]
@HazemAbdo what do u want to change?

**Comment by HazemAbdo** [comment]
1. The layout and the color of the cards are not very elegant so we can change the color to match the theme of the website, especially the home page.
2. Adding images for each topic 
3. Adding a small description for each topic on the card
4. Handling coming soon case.
![image](https://user-images.githubusercontent.com/59124058/169595764-fcf201a6-68c0-49f6-a14b-33ba43766394.png)

**Comment by HazemAbdo** [comment]
Using Bootstrap will be a big boost for the website UI

**Comment by Amit366** [comment]
@HazemAbdo we can't add images due to copyright issues, description for each specific topic is not possible as it will not maintain the column structure.
