### ISSUE TITLE
Adding a dedicated about us page

### ISSUE THREAD

**Issue by HazemAbdo** [Tech-N-Science/FunwithScience#653]
**Describe the bug**
Under GSSoC22
Add a separate page for the about us section as for now the about us and the home page are the same.If we will proceed with this option we will need some content about the website and its owners.
**Screenshots**
![image](https://user-images.githubusercontent.com/59124058/169650214-9ad34bc2-a82e-451a-9304-7f3e0aa021c5.png)
<img width="963" alt="image" src="https://user-images.githubusercontent.com/59124058/169650222-169bb07b-4a21-401b-bccf-b58892516314.png">

**Comment by Amit366** [comment]
@HazemAbdo this issue is already been created #389

**Comment by HazemAbdo** [comment]
> @HazemAbdo this issue is already been created #389 If u want u can work on adding solution to physics questions in the editorial section of each physics question

To make it clear you mean when the user press the editorial button a pop-up or another page will appear and will contain the solution in some details
<img width="975" alt="image" src="https://user-images.githubusercontent.com/59124058/169653108-38c8454c-b2b9-4bec-845f-90d83728058e.png">

**Comment by Amit366** [comment]
@HazemAbdo Another page will be opened where the user gets the entire solution for that particular question step wise. With proper explanation

**Comment by HazemAbdo** [comment]
> @HazemAbdo Another page will be opened where the user gets the entire solution for that particular question step wise. With proper explanation

I will make only the page(template) and use it for one question as an example then anyone more related to the content will use the template for all other questions.

**Comment by Amit366** [comment]
@HazemAbdo yes first let's see the template. See basically the writing part will be document so it will be markup language.

**Comment by HazemAbdo** [comment]
> @HazemAbdo yes first let's see the template. See basically the writing part will be document so it will be markup language. 
Ok I will create issue for it.
