### ISSUE TITLE
Adding an Editorial page  

### ISSUE THREAD

**Issue by HazemAbdo** [Tech-N-Science/FunwithScience#654]
Under GSSoC 22
Adding an Editorial page that contains a detailed solution for questions.
The solution will be in a markup language.

***Screenshots*
![image](https://user-images.githubusercontent.com/59124058/169655055-86a705c4-de78-435f-a6ac-8e0b2ff241be.png)

**Comment by Amit366** [comment]
@HazemAbdo try to send the pull request within 2 days
