### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Akanksha-Sen** [Tech-N-Science/FunwithScience#663]
I want to change the documentation of website, please assign me

**Comment by Amit366** [comment]
@Akanksha-Sen what documentation do u want to change?

**Comment by Akanksha-Sen** [comment]
I'd change some text and improve the content quality.

**Comment by Amit366** [comment]
@Akanksha-Sen if u want to change something in readme then there is nothing to improve and if u want to change something in the website then u should clearly mention what u would like to change. And u can dm in the discord what u would like to change.

**Comment by Amit366** [comment]
@Akanksha-Sen can u explain?

**Comment by Akanksha-Sen** [comment]
I'd improve the text part by enhancing the english words used. Sorry for the delay I had health issues.

**Comment by Amit366** [comment]
@Akanksha-Sen u can work
