### ISSUE TITLE
Footer margin is more than required

### ISSUE THREAD

**Issue by Harsh3363** [Tech-N-Science/FunwithScience#667]
**Describe the bug**
The margin from the bottom for the Footer is more than required.
**To Reproduce**

**Expected behavior**

**Screenshots**

![Screenshot (92)_LI](https://user-images.githubusercontent.com/72756692/182014280-5a85d554-2aaa-4d8c-bce9-0aa38bfe7a48.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Harsh3363** [comment]
Please assign this to me, I would be more than happy to fix this issue.
Thanks

**Comment by Sampurankishoresrivastava** [comment]
Please assign this to me.
Here are some sample of footers made by me in my projetcs.
[Files (1).zip](https://github.com/Tech-N-Science/FunwithScience/files/9283758/Files.1.zip)

**Comment by Amit366** [comment]
@Sampurankishoresrivastava this issue has been resolved
