### ISSUE TITLE
A new footer for the website

### ISSUE THREAD

**Issue by SushantPatial** [Tech-N-Science/FunwithScience#668]
I believe the footer doesn't go well with the website. Plus there's too much space below it. 

I want to build a new footer which fits the website.

Here are some of the designs I think will look good (I'll change the color scheme accordingly)

![image](https://user-images.githubusercontent.com/84243683/182958585-fd05a217-d3a1-4efa-8015-d44bef083df4.png)

![image](https://user-images.githubusercontent.com/84243683/182958499-cd2320c6-043c-4d71-8d8b-83c5261c0611.png)

![image](https://user-images.githubusercontent.com/84243683/182958882-87911a76-e939-4996-ab1a-a357a048dbdf.png)

**Comment by Amit366** [comment]
@SushantPatial u can work
