### ISSUE TITLE
Connect with us Buttons

### ISSUE THREAD

**Issue by Architsharma7** [Tech-N-Science/FunwithScience#674]
**Describe the bug**
All the buttons under the "Contact with us" section in the footer doesn't redirect to the website.

**To Reproduce**
1. Go to 'Readme file'
2. Click on 'Click on the website's link'
3. Scroll down to the 'footer on the contact with us section'
4. See an error.

**Expected behavior**
The social handle buttons should redirect to some pages.

**Desktop (please complete the following information):**
 - macOS
 - Chrome
 - 22

**Smartphone (please complete the following information):**
 - Device: Realme
 - OS: ANDROID
 - Browser: Chrome
 - Version: 22

I can fix this issue if you will assign it to me.

**Comment by Amit366** [comment]
@Architsharma7  the social handle buttons are not given any link so they are not directing. I think u should take up other issues
