### ISSUE TITLE
add periodic table in chemistry section

### ISSUE THREAD

**Issue by Amit366** [Tech-N-Science/FunwithScience#676]
**Is your feature request related to a problem? Please describe.**
in chemistry instead of calculators add periodic table and properties of different elements.

Replace calculator button with Formula in the drop down in home page and then create a page with two buttons periodic table and organic formulas. On clicking periodic table the periodic table should appear and also if possible add the properties of elements.

**Comment by Samiksha-Garg** [comment]
Hi, I would like to take this issue up. I plan on making a periodic table, and clicking on the element of interest, we can redirect user to the properties of that element.

**Comment by Amit366** [comment]
@Samiksha-Garg ok
