### ISSUE TITLE
social media icon of twitter,facebook and instagram not taking to link after click.

### ISSUE THREAD

**Issue by satyamkale27** [Tech-N-Science/FunwithScience#678]
**Describe the bug**
social media icon of twitter,facebook and instagram not taking to link after click.
**To Reproduce**
1. Scroll down to 'footer'
2. Click on 'social media icons'
3. See error

**Expected behavior
after clicking social media icon it should take to particular link

**Comment by satyamkale27** [comment]
i wish to work on this issue please give me the links of twitter,facebook and instagram

**Comment by Amit366** [comment]
@satyamkale27 because the links are not yet added. U can work on other issues
