### ISSUE TITLE
Calculate Inverse of a matrix

### ISSUE THREAD

**Issue by Samiksha-Garg** [Tech-N-Science/FunwithScience#681]
There doesn't exist a calculator to calculate inverse of a matrix. 

Under the algebra topics, I propose to have a calculator for calculating inverse of a matrix.

**Comment by Amit366** [comment]
@Samiksha-Garg u can add a section as matrix and accordingly u can add inverse, transpose, addition, subtraction. All in one section. Create different buttons

**Comment by Samiksha-Garg** [comment]
> @Samiksha-Garg u can add a section as matrix and accordingly u can add inverse, transpose, addition, subtraction. All in one section. Create different buttons

Okay. Do you want me to make a signle PR for them, or different PR for different operation?
