### ISSUE TITLE
Hacktoberfest logo doesn't display correctly on README.md

### ISSUE THREAD

**Issue by guiszk** [Tech-N-Science/FunwithScience#708]
**Describe the bug**
The Hacktoberfest logo doesn't display correctly on README.md, because the image source goes to a 404.

<img width="850" alt="Screen Shot 2022-10-22 at 3 28 28 PM" src="https://user-images.githubusercontent.com/23110500/197357316-62783315-b502-4cd2-b8c3-00cde2fdd8f8.png">

**To Reproduce**
View the #open-source-programs-we-have-been-associated-with section on README.

**Expected behavior**
The image should display correctly.

I can fix this, if you'd like!

**Comment by Amit366** [comment]
@guiszk u can fix that and also add social summer of code image along with the link to website

**Comment by HydraPhyzer** [comment]
Hey Sir, Could you please assign this task to me ?

**Comment by Amit366** [comment]
@guiszk u need to send the pull request to main repo and not the forked repo.
